### ISSUE TITLE
multi-variable LIST output has arbitrary limit on string length

### ISSUE THREAD

**Issue by karlmsmith** [NOAA-PMEL/Ferret#1026]
**Reported by @AnsleyManke on 20 Sep 2010 17:04 UTC**
strings are limited to 24 characters, so a list in the LAS_results script chops a variable name off.  Make this limit longer

(the ultimate fix for this may be to have Ferret list xml format for LAS.

Migrated-From: http://dunkel.pmel.noaa.gov/trac/ferret/ticket/1754

**Comment by AnsleyManke** [comment]
Closing this -- Ferret does write xml formatted output for LAS.
