### ISSUE TITLE
Loss of precision in multi-dimensional @SUM

### ISSUE THREAD

**Issue by karlmsmith** [NOAA-PMEL/Ferret#1041]
**Reported by ansley b manke on 30 Nov 2010 21:21 UTC**
Email from Andrew and coincidentally from Patrick Brockmann, http://www.pmel.noaa.gov/maillists/tmap/ferret_users/fu_2010/msg00712.html, have brought up the fact that the unweighted @SUM transformation is currently computed using single precision. Even when the sum is accumulated in a double-precision variable for each dimension, the fact that the intermediate results are passed back in single precision variables means a loss of precision.  

(clip from email, Hankin, 11/29/2010) It seems like a fairly straightforward matter (I don't think this is currently the case) to have multi-axis @SUM transformations be performed in a single block by DO_4D_TRANS.  We'd just need to follow the pattern of @DIN, @VAR, @NGD and @NBD. (Would need a tweak inside of DO_4D_TRANS to do efficient sums, much as is done with @ngd and @nbd.)
 . 
Then the results of @sum should become identical, whether done as a 1D XSEQUENCE or as a 2-D transformation.  It would be good to remove a source of evident alarm like this (It sounds like Patrick would be relieved.)

Migrated-From: http://dunkel.pmel.noaa.gov/trac/ferret/ticket/1769

**Comment by karlmsmith** [comment]
**Comment by ansley.b.manke on 5 Jan 2011 00:54 UTC**
This is fixed and will be in Ferret v6.66. Previously @SUM was done one dimension at a time, now it is done as a 4D operation, with one double-precision variable accumulating the sum.

**Comment by karlmsmith** [comment]
**Modified by ansley.b.manke on 5 Jan 2011 02:06 UTC**

**Comment by AnsleyManke** [comment]
This is checked in to the trunk and the pyFerret branch.
