### ISSUE TITLE
Zooming into a single grid cell in LAS generates an error.  Can be fixed.

### ISSUE THREAD

**Issue by karlmsmith** [NOAA-PMEL/Ferret#1105]
**Reported by steven.c.hankin on 14 Apr 2011 23:27 UTC**
In LAS currently, zooming in so far that the entire requested region lies inside of a single grid cell yields an error condition:

```
An error occurred in the service that was creating your product.
```

   Aside:  The actual error message from Ferret is much more informative: "**ERROR The xy region is too small. It reduces to a single point."

The reason that single point regions lead to an error condition in Ferret is that the desired plane of the plot is inferred from the data, itself.  A single point from a 4D region leaves the desired orientation ambiguous.  (The logic of this is found in ctx/plotify_grp_cx.F)  Other clues could be provided that would remove this ambiguity:
  1. look at hlim and vlim arguments, if provided
  2. add a new qualifier, say, /ORIENTATION=XY
  3. if an overlay, then remember the orientation from the last plot

Implementation of either 1 or 2 of these approaches would allow the problems of LAS zooms to go away.  Just need to ensure that the SHADE command, as given in the LAS Ferret scripts, has the necessary qualifier(s).

Note that the FILL command can do no plotting of data, if provided with only a single point.  But it need not generate an error condition.

Migrated-From: http://dunkel.pmel.noaa.gov/trac/ferret/ticket/1833

**Comment by karlmsmith** [comment]
**Comment by steven.c.hankin on 15 Apr 2011 15:57 UTC**
The analysis above was premature.  The routine ctx/plotify_grp_cx.F already contains logic that detects the correct orientation of the intended plot by looking at the requested world coordinate range -- which should work even if the span is only a single point.

It is in disp_set_up.F that the plot is terminated if the number of dimensions is not 2.  For the base plot (but not for overlays) this determination is based upon a look at GET_CX_DIMS, rather than nplot_axis.

The following **looks like** a bug in disp_set_up.F: isn't the decision to abort with error (msg at 5160) taken BEFORE the opportunity to check the lesser restrictions that are commented?  (ctx is the context of the first variable in the list)  Why not simply consult nplot_axis at this point?

```
* check for valid data plane
        CALL GET_CX_DIMS( ctx, ndim, dims )
        IF ( ndim .NE. 2 ) GOTO 5160
        IF ( overlay ) THEN
* *sh* 1/93 - restrictions less: coords merely have to be valid in 2D plane
           IF ( cx_lo_ss(ctx,dim1) .EQ. unspecified_int4
...
```

This faulty-seeming logic was added 11 years ago (by me) with the comment

```
	* V520   6/00 *sh* - bug fix: trap ndim>2 on overlays
```

Using totalview I ran this test script, which attempts to SHADE a single point:
```
use coads_climatology
shade/l=1 sst[x=170e:172e,y=0:2n]
```
While inside of DISP_SET_UP I allowed the code to bypass the faulty (?) test,
  "IF ( ndim .NE. 2 ) GOTO 5160"
I confirmed that Ferret did NOT crash, though the plot that it generated was whitw (not colored properly)

==> My belief is that we can remove the restriction on zooming down without a great deal of trouble.  (Need to look into SHADE, FILL, CONTOUR, and VECTOR separately.)

**Comment by karlmsmith** [comment]
**Comment by ansley.b.manke on 15 Apr 2011 16:28 UTC**
The message "ERROR The xy region is too small. It reduces to a single point." is coming from the LAS Ferret scripts, not from Ferret itself (but Ferret would return  **ERROR: dimensions improperly specified: must be a 2D region). 

The LAS scripts check the size of the requested region in index space and return that message if any dimension is 1. At the time we decided to return that message, I think we were talking about a different error response from LAS where the user would see the message rather than the "An error occurred in the service that was creating your product." The thought was that the message with "the nn region is to small" was friendlier than Ferret's own message.

The LAS scripts could instead return an image with a 1x1-cell plot, and perhaps also include a message if we want. 

So we could tweak the LAS Ferret scripts, or fix this as Steve outlines in the comment above.

**Comment by karlmsmith** [comment]
**Comment by steven.c.hankin on 15 Apr 2011 17:03 UTC**
We have 3 issues together here:
 1. Ferret scripts are returning "nice" error messages that are not being picked up and used by LAS.  '''This is a topic that you should take up with Roland''' -- how to allow LAS to pick up and display these special strings.  Our intention was for Ferret to be able to send informative messages to LAS users.  This could make significant usability improvements (provided that the scripts did a thorough job of this).    
 2. The Ferret script in LAS is presumably trapping the degenerate region as an error only because the current Ferret version would otherwise do so itself, and issue a less friendly message.  So if we enhance Ferret to make valid plots of degenerate regions, this trap would need to be removed from the script, too.
 3. I experimentally made the very small tweak to DISP_SET_UP of replacing "IF ( ndim .NE. 2 ) GOTO 5160" with "IF ( ndim .GT. 2 ) GOTO 5160".  The result was that.[[BR]]

  o SHADE plots did everything right **except** for not shading the colored region
  o FILL plots plotted nothing at all, but did not crash
  o  I did not (yet) test VECTOR

**Comment by karlmsmith** [comment]
**Comment by ansley.b.manke on 15 Apr 2011 18:02 UTC**
Cool.  A Vector plot needs a similar change in DISP_SET_UP, 

```
         ELSEIF ( vector) THEN     ! 1/94
            IF ( nplot_axis .NE. 2 ) GOTO 5160
```

should also be changed to .GT. 2

and then a single arrow is drawn.  Checking now on why colors don't show up on shade plots. This will mean that quite a bit of messy logic can be taken out of the Ferret LAS scripts.

**Comment by karlmsmith** [comment]
**Comment by ansley.b.manke on 16 Apr 2011 00:47 UTC**
The shade-plot code had a spot where it was assuming that nx>1 and ny>1. A minor change in ppl/tmapadds/shade.F takes care of that.

In addition, what if the region is degenerate only in one direction?  This is also a case that the Ferret LAS scripts detect. A further change in choose_cx_ww ensures that if there's just one point in the direction, then the renge along the axis is given as the lo and hi limits of the cell. We can have shade and vector plots where one of the regions has length 1.  I'm getting a color key on fill plots, which it'd be good to get rid of, and all this needs a bit more testing but this is a nice improvement to Ferret!

**Comment by karlmsmith** [comment]
**Comment by steven.c.hankin on 18 Apr 2011 23:19 UTC**
This is very good news.  It will be nice that overly-deep zooms in LAS no longer result in an error.  Having them result in a uniform colored data plot will feel natural to the user -- not like an error at all.

However, I do not understand why the case of degeneracy along 1 axis should require a fix in a different part of the code that degeneracy along 2 axes.  The reason that PLOTIFY_GRP_CX and DISP_SET_UP are able to handle the 2-axis degeneracy, is that the cx_lo/hi_ww limits remove the ambiguity about the orientation -- yes, the cx index space is just a single point, but the axes conveying the range were made clear through their world limits (ww_hi > ww_lo).  Why does this logic not work equally well for either a single or double degenerate axis region?

**Comment by karlmsmith** [comment]
**Comment by ansley.b.manke on 19 Apr 2011 00:41 UTC**
Regarding the last paragraph above, the cases where I had errors with the context were those with 1-by-n lines, but it may not really due to that detail but more in how the context is specified and what Ferret does with those specs. We might need to look further at this.  I was seeing differences in the limits for the plot axis depending on whether the center of the grid box or an edge was given, so that these two plots were different:

```
yes? shade/x=181/y=1
yes? shade/x=180/y=0
```

But also, when Ferret decides which directions to use for the plot dimensions, it's doing different things depending on whether subscripts or indices are used. In LAS it's always world coordinates that are handed to Ferret, but for instance, using the executable at

/home/users/ansley/linux/FERRET/fer/ferret_c

```
yes? use coads_climatology
yes? shade/x=180/y=0/L=1 sst
```

gives us a plot with Time on the horizontal axis and Latitude on the vertical axis.  But, using the world coordinate for time,

```
yes? shade/x=180/y=0/t=15-jan-0001 sst
```

results in a plot with Longitude on the horizontal axis and Latitude on the vertical. 

Likewise, 

```
yes? use ocean_atlas_subset
yes? shade/k=10/L=3/x=300/y=-40 temp  ! is a plot with lon & lat on the axes, but

yes? shade/k=1/L=3/x=300/y=-40 temp   ! has time & depth.
```

Interesting!!


-- in addition, perhaps the number of tic marks should be reduced for these plots.  Attaching an image where the plots are degenerate 2D regions, but one might be confused by the tic marks.




```
use ocean_atlas_subset
set view ul
shade/z=10/t=15-jun/x=300/y=-40/title="Point /z=10/t=15-jun/x=300/y=-40" temp
set view ur
shade/z=10/x=300/y=-40/title="Tline /z=10/x=300/y=-40" temp
set view ll
shade/L=3/x=180/y=-40/title="Zline /L=3/x=180/y=-40" temp
set view lr
shade/L=3/y=-40/z=0/title="Xline /L=3/y=-40/z=0" temp

```

**Comment by karlmsmith** [comment]
**Comment by ansley.b.manke on 19 Apr 2011 00:45 UTC**
The example with ocean_atlas subset should have had a Z=10 in the first line:
...Likewise,

```
yes? use ocean_atlas_subset
yes? shade/z=10/L=3/x=300/y=-40 temp  ! is a plot with lon & lat on the axes, but

yes? shade/k=1/L=3/x=300/y=-40 temp   ! has time & depth.
```

**Comment by karlmsmith** [comment]
**Comment by steven.c.hankin on 19 Apr 2011 15:58 UTC**
I think maybe we are going to far in the solution.  If the orientation of the base plot is inappropriate, as it is with
```
shade/z=10/L=3/x=300/y=-40 temp
```
then it is fine to respond with an error.  These command qualifiers have provided an unambiguous point location in X, Y, and Z, and a probable point location in T (L).  It seems like the only right behavior is to regard this as an erroneous command -- such a region cannot be SHADEd.

The purpose of this ticket is to resolve the problems in LAS.  Since LAS always provides ranges given as world coordinates, that is why it seemed like the logic found in PLOTIFY_GRP_CX -- which is able detect a clear 2D intention, even when the grid subset degenerates to a point -- would be sufficient.

**Comment by karlmsmith** [comment]
**Comment by ansley.b.manke on 20 Apr 2011 19:48 UTC**
In the example with 

```
shade/k=1/l=3/x=300/y=40 temp
```

at the point when plotify_grp_cx runs, the ww context for z and t has been filled in with the high and low box limits so PLOTIFY_GRP_CX promotes the ZT region as a 2D region for the plot. Only for the cmnd_cx is the world context not filled in.

Should we be using cx_cmnd in plotify_grp_cx when testing whether degenerate regions can be promoted?

**Comment by karlmsmith** [comment]
**Comment by steven.c.hankin on 20 Apr 2011 23:15 UTC**
The superficial answer is that in plotify_grp_cx we should be able to consult the variable cx_by_ss to see whether limits were specified as indices (TRUE) or by world coordinates (FALSE).  The logic would then be that a given axis '''does''' have a range specified if

```
  cx_hi_ss > cx_lo_ss
OR
  cx_hi_ww > cx_lo_ww AND .NOT.cx_by_ss  
```

This may be all that is needed to solving the problem for LAS deep zooms.

---

For Ferret perfection there may be subtler cases, like ranges that are embedded into a LET definition.  e.g.

    LET my_sst = sst[x=170w:160w]

Can cx_by_ss be trusted on the X axis of a plot of the definition of my_sst, above?  I'm not sure.  Need to test.

If problems emerged you'd probably need to expand the logic of plotify_grp_cx to consult
  cx_category -- is it a LET-defined variable?  ... if yes then
  cx_given -- was this axis range specified in the command?  ... if no then
  follow the same logic as the simple case above, but instead of consulting cx_by_ss, and cx_lo/hi_ss/ww you'd consult uvar_by_ss, and uvar_lo/hi_ss/ww to see the specifications given inside the LET definition, itself.

Note: In some extreme situations of nested, crazy LET definitions even this might not give the correct answer.  But the consequences of that extreme situation slipping through would be very small.

**Comment by karlmsmith** [comment]
**Comment by steven.c.hankin on 21 Apr 2011 17:46 UTC**
Just a short post script to explain why the a point location specified as a subscript, becomes a world coordinate range in cx_lo/hi_ww.  It happens in FLESH_OUT_AXIS

```
        ELSEIF ( cx_by_ss( idim, cx ) ) THEN
* POSITIONS WERE SPECIFIED BY SUBSCRIPT
[...snip...]

* compute world positions as grid box edges
           cx_lo_ww(idim, cx) = TM_WORLD( cx_lo_ss( cx,idim),
     .                                    grid, idim, box_lo_lim )
           cx_hi_ww(idim, cx) = TM_WORLD( cx_hi_ss( cx,idim),
     .                                    grid, idim, box_hi_lim )
```

This logic makes perfect sense when there is a subscript range -- i.e. cx_hi_ss.GT.cx_lo_ss -- representing the full ww range of those grid cells.  It is tempting to think, though,  if cx_lo_ss.EQ.cx_high_ss, FLESH_OUT_AXIS should instead insert the ww location of the grid point.  But memory cache hits could be adversely effected.  Logic found in places like LOHI_WORLD shows that a single point subscript is correctly interpreted as a point ww position.

```
* is this just a single grid box with the world coord bod edges given ?
 200    IF ( cx_lo_ss(cx,idim) .NE. unspecified_int4
     .  .AND.cx_lo_ss(cx,idim) .EQ. cx_hi_ss(cx,idim) ) THEN
           lo = TM_WORLD( cx_lo_ss(cx,idim),grid, idim, box_middle )
           hi = lo
```

**Comment by karlmsmith** [comment]
**Attachment from ansley.b.manke on 19 Apr 2011 00:42 UTC**
from the script in comment 7
REPLACE THIS TEXT WITH UPLOADED FILE ./attachments/TRAC_1833_GIT_1105/1833.gif

**Comment by AnsleyManke** [comment]
This is fixed, long since. If we zoom in so the region represents just one grid cell or a portion of a grid cell, the plot that's returned is just a rectangle filled with color.
