### ISSUE TITLE
let a = {spawn:" command"} not disallowed in secure mode

### ISSUE THREAD

**Issue by karlmsmith** [NOAA-PMEL/Ferret#1199]
**Reported by @AnsleyManke on 12 Mar 2012 17:34 UTC**
Patrick Brockmann reports:

I use ferret -secure option to disable
call to spawn command but I have noticed
that I still can do:

```
let a={spawn:"touch file"}
```
Or try,

```
> ferret -secure
yes? let a={spawn:"ls"}
yes? list a
             VARIABLE : {SPAWN:"ls"}
             SUBSET   : 42 points (X)
 1    /  1:"aa.nc"                        
 2    /  2:"b1.jnl"                  
 ...
```

In the call to spawn from xeq_spawn.F, there is a check for secure mode, but the above uses a call to get_sys_cmnd.  The path to this is the Fortran routine store_sys_strings, which should have a check for secure mode.

Note this is NOT new behavior, I see it back to at least Ferret v5.81 

Migrated-From: http://dunkel.pmel.noaa.gov/trac/ferret/ticket/1927

**Comment by AnsleyManke** [comment]
This is fixed in do_internal_gc_fcn.F and in store_sys_strings.F, - set an error condition and issue a message.
