### ISSUE TITLE
bug in `@XACT` regridding in double-precision Ferret

### ISSUE THREAD

**Issue by karlmsmith** [NOAA-PMEL/Ferret#1238]
**Reported by @AnsleyManke on 11 Sep 2012 23:21 UTC**
This is seen in this Users List thread:
! http://www.pmel.noaa.gov/maillists/tmap/ferret_users/fu_2012/msg00477.html

Example:

```
Let time = {\
 22585.3295833333,\
 22585.3302777778,\
 22585.3309722222,\
 22585.3316666667,\
 22585.3323611111,\
 22585.3330555556,\
 22585.33375,\
 22585.3344444444,\
 22585.3351388889,\
 22585.3358333333}
 
Define Axis /T /From /T0=1-JAN-1950 /Units=days my_axis = time
 
Let fake_var = T[GT=my_axis]
Let var = RANDU( fake_var )
Let var_regrid = RESHAPE( var, fake_var )
 
List /T="2-nov-2011 07:54":"2-nov-2011 08:04" var_regrid
             VARIABLE : RESHAPE( VAR, FAKE_VAR )
             SUBSET   : 10 points (TIME)
 02-NOV-2011 07:54:36 /  1:  0.6251
 02-NOV-2011 07:55:36 /  2:  0.2209
 02-NOV-2011 07:56:36 /  3:  0.6074
 02-NOV-2011 07:57:36 /  4:  0.3226
 02-NOV-2011 07:58:36 /  5:  0.1075
 02-NOV-2011 07:59:36 /  6:  0.2257
 02-NOV-2011 08:00:36 /  7:  0.0811
 02-NOV-2011 08:01:36 /  8:  0.8980
 02-NOV-2011 08:02:36 /  9:  0.7163
 02-NOV-2011 08:03:36 / 10:  0.6649
 
! Note that if we define the axis as below, the regridding is
! successful. But the `@XACT` regridding in v6.82 was requiring too
! much matching precision.
 
!    DEFINE AXIS/t="02-nov-2011:07:54:36":"02-nov-2011:08:03:36":60/units=seconds/T0=1-JAN-1950 my_axis
!    let time = t[gt=my_axis]
!    Let var = TSEQUENCE( RANDU( time ) )
!    Let fake_var = T[GT=my_axis]
!    Let var_regrid = RESHAPE( var, fake_var )
 
! New time axis
Define Axis /T="01-NOV-2011 00:00":"30-NOV-2011 23:00":1 /Units=seconds /T0=1-JAN-1950 t_axis_seconds
 
Let var_sec = var_regrid[ GT=t_axis_seconds`@XACT` ]
 
! Here we got no good data, should be one at 7:54:36.
 
List /T="2-nov-2011 07:54:30":"2-nov-2011 07:54:50" var_sec
             VARIABLE : VAR_REGRID[ GT=T_AXIS_SECONDS`@XACT` ]
             SUBSET   : 21 points (TIME)
 02-NOV-2011 07:54:30 / 114871:....
 02-NOV-2011 07:54:31 / 114872:....
 02-NOV-2011 07:54:32 / 114873:....
 02-NOV-2011 07:54:33 / 114874:....
 02-NOV-2011 07:54:34 / 114875:....
 02-NOV-2011 07:54:35 / 114876:....
 02-NOV-2011 07:54:36 / 114877:....
 02-NOV-2011 07:54:37 / 114878:....
 02-NOV-2011 07:54:38 / 114879:....
 02-NOV-2011 07:54:39 / 114880:....
 02-NOV-2011 07:54:40 / 114881:....
 02-NOV-2011 07:54:41 / 114882:....
```

There should be a value at 02-NOV-2011 07:54:36 

The regridding code gets the coefficients for a linear regridding operation, and then sees which indices correspond to an "exact" regridding, that is coefficients = 0. It has always used a single-precision comparison call to TM_FPEQ to check for that. In the conversion to double precision, we mistakenly went to a double-precision comparison.  As the coordinate data hasn't changed; it's always been double precision, the fix is to restore the use of a single-precision version of TM_FPEQ.

Migrated-From: http://dunkel.pmel.noaa.gov/trac/ferret/ticket/1966

**Comment by AnsleyManke** [comment]
A fix was made but this ticket hadn't been closed.  Another example came up:


Using the single-precision comparison of coordinates as implemented isn't enough.  Here's another axis, which is almost but not quite a regular hourly axis.  We want to regrid to a defined hourly axis.  
```

Let time = {\
   221.0000000000000,\
   221.0416666666280,\
   221.0833333333720,\
   221.1250000000000,\
   221.1666666666280,\
   221.2083333333720,\
   221.2500000000000,\
   221.2916666666280,\
   221.3333333333720,\
   221.3750000000000,\
   221.4166666666280}
define axis/t/t0=1-jan-2018/units=days my_axis = time
let var = L[gt=my_axis]

define axis/t="10-aug-2018 00:00":"10-aug-2018 10:00":`1/24`/units=day/t0="1-jan-2018 00:00" CO2_hrly_ax

let var_on_reg = var[gt=CO2_hrly_ax@xact]

yes? list var_on_reg
             VARIABLE : VAR[GT=HRLY_AX@XACT]
             SUBSET   : 11 points (TIME)
 10-AUG-2018 00:00:00 /  1:  1.000
 10-AUG-2018 01:00:00 /  2:  2.000
 10-AUG-2018 02:00:00 /  3:  2.000
 10-AUG-2018 03:00:00 /  4:  4.000
 10-AUG-2018 04:00:00 /  5:  5.000
 10-AUG-2018 05:00:00 /  6:  5.000
 10-AUG-2018 06:00:00 /  7:   ....
 10-AUG-2018 07:00:00 /  8:  7.000
 10-AUG-2018 08:00:00 /  9:  7.000
 10-AUG-2018 09:00:00 / 10:  9.000
 10-AUG-2018 10:00:00 / 11:   ....

```
... it should be

```
 10-AUG-2018 00:00:00 /  1:  1.000
 10-AUG-2018 01:00:00 /  2:  2.000
 10-AUG-2018 02:00:00 /  3:  3.000
 10-AUG-2018 03:00:00 /  4:  4.000
 10-AUG-2018 04:00:00 /  5:  5.000
 10-AUG-2018 05:00:00 /  6:  6.000
 10-AUG-2018 06:00:00 /  7:   ....
 10-AUG-2018 07:00:00 /  8:  7.000
 10-AUG-2018 08:00:00 /  9:  8.000
 10-AUG-2018 09:00:00 / 10:  9.000
 10-AUG-2018 10:00:00 / 11:   ....
```
In routine get_linear_coef, the correct result for this second example is in using TM_FPEQ_SNGL instead of just comparing SNGL(xsrc) and SNGL(xdst). 


Rather than a single-precision comparison of coordinates, which might not be enough to distinguish them, we need to use a tolerance based on the magnitude and resolution of the coordinates.

**Comment by AnsleyManke** [comment]
The XACT regridding needs some different logic from other regridding operations, at the point of deciding which grid cells from the source axis map to the destination axis.  For linear, or average, or nearest regridding that's a matter of locating the grid cells, but for XACT regridding, the operation needs enough precision so the code can decide if the coordinates really match.  If the coordinates are varying only in the 9th decimal place we can't use a single-precision comparison.

I've added a new routine to be used for XACT, get_coef_for_xact.  This uses a tolerance for comparing coordinate values, based on the delta-coordinate values and the magnitude of the coordinates.
