### ISSUE TITLE
documenting computing climatologies:  true calendar month boundaries

### ISSUE THREAD

**Issue by karlmsmith** [NOAA-PMEL/Ferret#1306]
**Reported by @AnsleyManke on 31 Jan 2013 01:01 UTC**
@MOD computes the resulting monthly averages as an equal weighting of all points that lie within the target (modulo-wise) grid cell, i.e. all points in March in the source axis are averaged to yield the March climatology value.

This may create unexpected biases, if, say, 1995 has 2 points lying in March and 1996 has 5 points in that same month.  That deserves a comment in the documentation.

In addition, the commonplace (sloppy) way that most climatologies are computed is that all data falling within a particular calendar month boundary go into the computed average of that month of the climatological average.  If we regard the climatological year as a representation of the earth's tilt relative to the sun (the solar year), then this way of computing climatological averages means that there are small alterations (up to ~3/4 day errors) in the mapping of the calendar months onto the climatological year based on leap year variations.  Since such calculations are commonplace (even if sloppy), the technique for achieving them in Ferret should be clearly documented in the User's Guide.

To do it carefully, average in 2 stages:
1) average the original (say, daily) data onto a true-month Gregorian calendar axis using @ave.  This calculation will respect the calendar month boundaries, including leap years. The target climatology axis could be used, specifying the input date range, and using @AVE rather than @MOD.

2) Now do the modulo regridding from this monthly average.

We need an FAQ on this as well as notes and cross-references between discussions of Climatologies and Modulo regridding in the Users Guide.

Migrated-From: http://dunkel.pmel.noaa.gov/trac/ferret/ticket/2034

**Comment by karlmsmith** [comment]
**Comment by steven.c.hankin on 31 Jan 2013 17:45 UTC**
I think we should '''consider''' adding a new set of "climatological" regridding transforms that perform the transformations in 2-steps instead of all at once ( step 1:average each year; step 2: average the year aves )

   @mod    ==> @clim
   @modvar ==> @climvar

Putting this into the documentation and release notes, would provide a way to make users more aware of the difference and significantly decrease the occasions of accidentally using the wrong algorithm.

**Comment by AnsleyManke** [comment]
This is done in the FAQ How do I calculate climatologies and climatological anomalies? and in the documentation under the @MOD transformation.
