### ISSUE TITLE
immediate mode RETURN=LSIZE returns wrong size for pseudovariable

### ISSUE THREAD

**Issue by karlmsmith** [NOAA-PMEL/Ferret#1323]
**Reported by @AndrewWittenberg on 13 Mar 2013 21:39 UTC**
Ferret v6.85 incorrectly returns "1" for the size of an axis of a pseudo-variable built from the two variables, one of which is transformed and one of which isn't.

Version 6.841 behavior gets the first and third answers right.  The second answer isn't really right, but at least it reflects the compute domain:

```
 	NOAA/PMEL TMAP
 	FERRET v6.841  
 	Linux 2.6.32-279.19.1.el6.x86_64 64-bit - 01/25/13
 	13-Mar-13 17:26     

yes? use coads_climatology
yes? say `sst,r=lsize`
12
yes? say `sst[t=`@ave`],r=lsize`
12
yes? say `sst-sst[t=`@ave`],r=lsize`
12
```

In v6.85, the second answer is right, but the third is definitely wrong:

```
 	NOAA/PMEL TMAP
 	FERRET v6.85 (beta)
 	Linux 2.6.32-279.22.1.el6.x86_64 64-bit - 02/20/13
 	13-Mar-13 17:25     

yes? use coads_climatology
yes? say `sst,r=lsize`
12
yes? say `sst[t=`@ave`],r=lsize`
1
yes? say `sst-sst[t=`@ave`],r=lsize`
1
```

Migrated-From: http://dunkel.pmel.noaa.gov/trac/ferret/ticket/2051

**Comment by karlmsmith** [comment]
**Comment by ansley.b.manke on 7 May 2013 23:47 UTC**
See ticket #1801, where we added code in interp_context.F to look at  uvar_given(idim,uvar) and if it's uvlim_need_xact, unset the context subscripts. This means that


```
say `sst[used to return 12 now correctly says 1. 

However, for compound expressions, merge_grid sets the value of uvar_given(idim,uvar) to a different value depending on the ordering of the sub-expressions(!) So, adding to Andrew's example above,

```
yes? say `sst[t=@ave](t=@ave],r=lsize`
```


which)-sst,r=lsize`
 !-> MESSAGE/CONTINUE 12
12
```

**Comment by karlmsmith** [comment]
**Comment by ansley.b.manke on 8 May 2013 21:37 UTC**
This is fixed, so that the internal flag for what context information the user variable has and what it needs is now consistent for expressions with multiple sub-expressions. 
```

yes? use coads_climatology
yes? say `sst,r=lsize`
 !-> MESSAGE/CONTINUE 12
12
yes?  say `sst[!-> MESSAGE/CONTINUE 1
1
yes? say `sst-sst[t=@ave](t=@ave],r=lsize`
),r=lsize`
 !-> MESSAGE/CONTINUE 12
12
```

and, all of these below should return XYT.  In our beta version of Ferret v685, they were retyrning XY, YT, and XY:

```
yes? use coads_climatology
yes? say `sst-sst[!-> MESSAGE/CONTINUE XYT
XYT
yes? say `sst-sst[t=@ave](t=@ave],r=shape`
)+sst[,r=shape`
 !-> MESSAGE/CONTINUE XYT
XYT
yes? say `sst-sst[x=@ave](x=@ave])+sst[t=@ave] ,r=shape`
 !-> MESSAGE/CONTINUE XYT
XYT
```


Additional tests have been added to the benchmark suite.

**Comment by AnsleyManke** [comment]
This is fixed. We'll get you an updated build.

The code for RETURN= calls a set of the routines that are used as Ferret evalulates the context for the different elements of an expression.  The previous fix is just what we want for RETURN= but it changed a routine common to both paths of the code.  

Set a flag so the routine knows when we're doing RETURN=and when we're doing a full evaluation.

I think this logic might be used to give better results for SHOW GRID, which currently just gives info about the axes of the grid but not their size as they'll be in the result.  I'll open a new ticket on that.
