### ISSUE TITLE
Ferret syntax to define a global attribute when writing a netCDF file

### ISSUE THREAD

**Issue by karlmsmith** [NOAA-PMEL/Ferret#1332]
**Reported by @AnsleyManke on 10 Apr 2013 22:32 UTC**
We always refer to datasets by the variables they contain, so direct syntax for writing a new global attribute is not natural.  However, we can define the attribute using the same syntax as for getting a global attribute,

define att ..attname = "string"

and then on the next save of a variable to the dataset, the attribute is written:

```

yes? use coads_climatology
yes? let var = 2*sst

yes? define attribute ..my_new_global = "A global attribute"
yes? define attribute ..Global_2 = "A second global attribute"

yes? save/append/file=a.nc airt
yes? save/clobber/file=aa.nc var

yes? sp ncdump -h aa.nc
netcdf aa {
dimensions:
...
// global attributes:
                :history = "FERRET V6.85   10-Apr-13" ;
                :Conventions = "CF-1.0" ;
                :myglobal = "my new global attribute" ;
                :another_att = "my next new global attribute" ;


yes? ! Continuing,
yes? def att ..third_att = "even another global attribute"
yes? save/file=aa.nc/append sst
yes? sp ncdump -h aa.nc 
netcdf aa {
...
// global attributes:
                :history = "FERRET V6.85   10-Apr-13" ;
                :Conventions = "CF-1.0" ;
                :myglobal = "my new global attribute" ;
                :another_att = "my next new global attribute" ;
                :third_att = "even another global attribute" ;


yes? cancel attribute ..another_att

yes? save/file=bb.nc/CLOBBER sst
yes? sp ncdump -h bb.nc
netcdf bb {
dimensions:
...
// global attributes:
                :history = "FERRET V6.85   10-Apr-13" ;
                :Conventions = "CF-1.0" ;
                :my_new_global = "A global attribute" ;
                :third_att = "even another global attribute" ;
}

```

So we can do this, even if it's a little kludgy.  Needs documentation, and an FAQ.

Migrated-From: http://dunkel.pmel.noaa.gov/trac/ferret/ticket/2060

**Comment by karlmsmith** [comment]
**Comment by ansley.b.manke on 10 Apr 2013 22:34 UTC**
just cleaning up a typo, extra line.

**Comment by karlmsmith** [comment]
**Comment by steven.c.hankin on 3 Feb 2016 18:34 UTC**
I'm still getting my arms around the use of attributes, so may have misunderstandings.  My question is this:
Ferret offers three places to set the "context"
  1. from SET commands  (SET REGION/X)
  2. ... over-ridden by qualifiers (/X=lo:hi)
  3. ... over-ridden by square brackets (var[script at bottom that generates the test files)

For attributes of variables the syntax seems to exist to do the equivalent, but it looks like there is a bug (note "[d=2](x=lo:hi])

(see)" in brackets, but "f3.nc" listed:

```
yes? list/d=2 sst.units
             VARIABLE : SST.UNITS
             FILENAME : f2.nc
             X        : 1
        "Deg C"

yes? list sst[            VARIABLE : SST[D=f2](d=2].units
).UNITS
             FILENAME : f3.nc
             X        : 1
        "Deg C"

```

(Might this bug have come from recent changes due to the discussions of square bracket parsing was occurring in some utility functions?)  

Assuming the last command had worked as expected, is there a square bracket syntax to explicitly indicate which is the context dataset of a '''global''' attribute?  

===========================
Script to generate test files:

```
use coads_climatology

define attribute ..my_new_global = "File 1 global attribute"
save/clobber/file=f1.nc sst[ncdump -h f1.nc |tail -3

define attribute ..my_new_global = "File 2 global attribute"
save/clobber/file=f2.nc sst[l=1](l=1]
sp)
sp ncdump -h f2.nc |tail -3

define attribute ..my_new_global = "File 3 global attribute"
save/clobber/file=f3.nc sst[l=1]
sp ncdump -h f3.nc |tail -3
```

**Comment by karlmsmith** [comment]
**Comment by ansley.b.manke on 3 Feb 2016 23:30 UTC**
This does look like a lack in the parsing the syntax when a . appears in a variable name.  What works correctly is:

```

yes? list/d=2 sst.units
             VARIABLE : SST.UNITS
             FILENAME : f2.nc
             X        : 1
        "Deg C"

yes? list sst.units[            VARIABLE : SST.UNITS[D=f2](d=2]
)
             FILENAME : f2.nc
             X        : 1
        "Deg C"

```

and in fact this is documented,


''When there is more than one dataset open, the dataset specifier [or [d=datasetname](d=1]) comes at the end of the varname.attname string:

... 
yes? list var.units[d=1]
''

**Comment by karlmsmith** [comment]
**Comment by ansley.b.manke on 3 Feb 2016 23:47 UTC**
When initializing a dataset we read the header and store everything in the linked-list structure.  (A basic version of this is also done for non-netCDF datsets.) Then in a second step, Ferret reads that and populates the arrays that store variables, axes, units, etc. So far so good.


DEFINE ATTRIBUTE goes and makes a new entry into the linked-list attribute structure for a variable in a dataset.  Adding new attributes to file variables adds that information to the linked list structure for that file.  User-defined variables and their attributes are added to the uvar_dset  (dset=-1), and attributes for user-defined variables are stored there.  So, here's the question: 

Currently newly defined global attributes are added to the current default dataset. If there is no default dataset, then what?  They probably can be added to the virtual uvar_dset.

Then a new option for SAVE,


```
yes? define attribute ..my_new_global = "something"
yes? save/attribute/file=filename.nc ..my_new_global  
```

would go look for the global attribute my_new_global in the uvar_dset set of global attributes.

We could also get global attributes from another dataset and write them to our file.


```
yes? save/attribute/file=filename.nc ..institution[d=2]
```


The above should have /append (could a file be written with only global attributes with save/clobber/file=a.nc ..global_att ??)

The /ATTRIBUTE qualifier may not be necessary.  When parsing the argument, Ferret will detect that it's a varname.attname, and act accordingly.

**Comment by karlmsmith** [comment]
**Comment by steven.c.hankin on 4 Feb 2016 02:43 UTC**
[responding off-the-cuff.  Have not gone into the code to investigate answers to these questions.
AND have made major edits since the first version of these comments -- ignore version 1](disclaimer:
I'm)


  1. First a quick comment regarding the syntax, "sst[ I didn't realize this wasn't the right syntax.  However, Ferret let me down by accepting this as if it were a valid syntax.  It should catch and report the error, don't you think?

  2. It sounds like "..my_new_global[d=2](d=2].units".)" is a valid syntax, right?  If so, that's great.  A way is needed to identify the dataset of the global attribute.

  3. A question about your statement "User-defined variables and their attributes are added to the uvar_dset (dset=-1)":  this makes sense for global variables, but is it true of variables defined with LET/D as well?

  4. You pose the question "If there is no default dataset, then [does your global attribute definition get put](where)?".  It's a good question, because if I issue "define attribute ..my_new_global = "something" as the very first command in a new session no error is generated.  Where was that global attribute assigned, and how is it accessed?

  5. I like your proposed syntax:

```
yes? save/append/file=filename.nc ..institution[for that matter

```
yes? save/append/file=filename.nc sst.units[d=2](d=2]
```

and)
```

This syntax would essentially offer (limited) direct editing of the attributes in a netCDF file -- as opposed to the approach where attributes are always handled as appendages of variables being written.  For many situations, this seems friendlier and easier. 

Still, we have not solved the problem of cleanly of putting global attributes into a dataset, independent of the variables.  How about this syntax

```
DEFINE ATTRIBUTE/D=* ..institution = "PMEL"
SAVE/file=myfile.nc sst, ..institution[d=*]
```

"*" in this outlook refers to the "global" dataset. By this logic "LET/D=* ..." would also be an acceptable syntax.  It would be equivalent to plain-old "LET";  it would define a global variable. Doesn't seem hard to implement.  (This approach may also provide Karl with a nice way to talk to global variables from pyferret.)

By the way, a minor awkwardness that I stumble over from time to time is the inconsistency of a "show data/att dname" but no "show var/att vname".  Maybe in the code show var/att could be quickly implemented by redirecting itself to show att/var (??)

**Comment by karlmsmith** [comment]
**Comment by ansley.b.manke on 4 Feb 2016 17:42 UTC**
The attribute-handling has two holes, as implemented now: 1) Very little functionality with global attributes, and 2), incorrect behavior with respect to LET/D=n variables.

>
>    1. First a quick comment regarding the syntax, "sst[ I
>  didn't realize this wasn't the right syntax.  However, Ferret let me down
>  by accepting this as if it were a valid syntax.  It should catch and
>  report the error, don't you think?
>
yes, either this should be valid, or an error should be returned.

>
>
>    2. It sounds like "..my_new_global[d=2](d=2].units".)" is a valid syntax, right?  If
>  so, that's great.  A way is needed to identify the dataset of the global
>  attribute.

Yes, that's the right syntax, but it isn't hooked up to work that way now.
>
>    3. A question about your statement "User-defined variables and their
>  attributes are added to the uvar_dset (dset=-1)":  this makes sense for
>  global variables, but is it true of variables defined with LET/D as well?

I've been working on this, http://dunkel.pmel.noaa.gov/trac/ferret/ticket/2352
Currently LET/D variables are put into the uvar_dset. Which means that if the same variable name is defined, "LET/D=1 var=expr", and "LET/D=2 var=expr2", the information in the structure for previous definitions of variable "var" are lost. They should be added to the structure for dset=n.  There was some minor hang-up on the (little-used?) LET/D definition, where no dataset is given,

''http://ferret.pmel.noaa.gov/Ferret/documentation/users-guide/commands-reference/DEFINE#_VPINDEXENTRY_1355
    ...If the /dataset qualifier is applied without specifying a data set name then the interpretation is different. In this case the named variable becomes a default definition -- one which applies only if a data-set specific variable of the same name does not exist.'' 

Other than that wrinkle, this is straightforward.

>
>    4. It would be nice if DEFINE ATTRIBUTE shared the behavior of other
>  commands in terms of how it determines the dataset: the default dataset;
>  over-ridden by the command qualifier;  over-ridden by the variable
>  qualifier.  Per this logic we'd have  DEFINE ATTRIBUTE/D=2 ..my_new_global
>  and we'd have DEFINE ATTRIBUTE ..my_new_global[ Are
>  these currently supported?
>
This is implemented for variable attributes but not for global ones. I agree this is the right behavior and a consistent syntax. 
>
>
>    5. You pose the question "If there is no default dataset, then [where
>  does your global attribute definition get put](d=2])?".  It's a good question,
>  because if I issue "define attribute ..my_new_global = "something" as the
>  very first command in a new session no error is generated.  Where was that
>  global attribute assigned, and how is it accessed?  I'd want to pose a
>  different question, though:  "How do you control the dataset to which your
>  attribute definition applies?  Bullet number 4 just above would address
>  this question for all cases except the "global" (a.k.a. "abstract")
>  dataset.  A syntax to indicate the global dataset would round things out.
>  Say: 'DEFINE ATTRIBUTE ..my_new_global[= "something"'.  ("*" is a
>  nice symbol if we call it the "global" dataset).  By this logic "LET/D=*
>  ..." is equivalent to plain-old "LET".  It may provide Karl a way to talk
>  to global variables from pyferret.
>
Good thoughts. The commend DEFINE ATT ..new_global_att = currently is applied to the default dataset. If it's given with no dataset open, it isn't stored.  And no error message is given. 
>
>    6. I like your proposed:
>
>  ```
>  yes? save/append/file=filename.nc ..institution[d=2](d=*])
>  ```
>
>  If the implementation of the 3-level nested -- 1.set-default/2.command-
>  qualifier/3.variable-qualifier -- behavior is likely to require a lot of
>  code changes, then this might be the opportunity to apply that period of
>  re-write that you talked to Eugene about.  Another minor awkwardness I
>  stumble over from time to time is the inconsistency of a "show data/att
>  dname" but no "show var/att vname".

Here the syntax is SHOW ATT varname, in parallel with DEFINE ATT, CANCEL ATT.

```
yes? use coads_climatology
yes? sh att sst
     attributes for dataset: /home/users/tmap/ferret/linux/fer_dsets/data/coads_climatology.cdf
 SST.missing_value = -1.E+34
 SST._FillValue = -1.E+34
 SST.long_name = SEA SURFACE TEMPERATURE 
 SST.history = From coads_climatology 
 SST.units = Deg C
```
 
There could be a SHOW VAR/ATT for better symmetry with other commands.

**Comment by karlmsmith** [comment]
**Comment by ansley.b.manke on 8 Nov 2017 00:53 UTC**
I've implemented a simple way to write out a variable as a global attribute to a netCDF file.

yes? SAVE/ASGLOBAL/file=fname.nc var

It requires that the variable be 1-dimensional. It can be numeric or a string. If a string, then (for now anyway) I require it to be a single string. It even works if the file named does not yet exist, in which case we write a file with just the default Ferret global attributes, and the specified new one.

The syntax 
  set att/output=all .  

will be useful to inherit existing attributes from a file to a new file being written but this will give lots of flexibility to create and write new attributes without all the awkwardness of the things in the above discussion.

Will write an FAQ about handling global attributes.

**Comment by AnsleyManke** [comment]
This fails for scalar numeric variables,

```
yes? let gnum = 12.5
yes? save/append/file=filename.nc/asglobal gnum
```

Writes a global attribute that's a blank string:
```
// global attributes:
                :history = "FERRET ..." ;
                :Conventions = "CF-1.6" ;
                :GNUM = "" ;
```

**Comment by AnsleyManke** [comment]
This is fixed in cdf_list.F
```

yes? let gnum = 12.5
yes? let inum = 13.1

 yes? save/append/file=filename.nc/asglobal/ gnum
 yes? save/append/file=filename.nc/asglobal/outtype=int inum
```
results in this in the file,

```
// global attributes:
                :history = "FERRET V7.41 (beta/debug)  6-Jun-18" ;
                :Conventions = "CF-1.6" ;
                :GNUM = 12.5 ;
                :INUM = 13 ;

```
