### ISSUE TITLE
STAT command truncates # good or # bad at 8 digits

### ISSUE THREAD

**Issue by karlmsmith** [NOAA-PMEL/Ferret#1420]
**Reported by ansley b manke on 5 Mar 2014 00:18 UTC**
Keith Dixon ran into this. He has a variable on a 194 x 114 grid with 30 years of daily data (10958 time levels) for a total of 242,347,128 data points. 

He used STAT to see how many good and bad data were present in a result (one could use @NGD here instead).  His result of STAT shows:

 Total # of data points: 24234712  (194*114*1*10958*1*1)
 # flagged as bad  data: 24234712

it should be...

 Total # of data points: 242347128 (194*114*1*10958*1*1)
 # flagged as bad  data: 242347125
                                 ^

Here's a script we can run:

```
yes? use etopo5
yes? set mem/siz=2400

yes? define axis/t=1:50:1 tax
yes? let roseyt = if rose le -7000 then rose +0*t[! This is the number of points in the grid:
yes? list/prec=10 `rose,return=isize`*`rose,return=jsize`*50
 !-> list/prec=10 4320*2161*50
             VARIABLE : 4320*2161*50
          466776000.0

yes? stat roseyt
 
             IF ROSE LE -7000 THEN ROSE +0*T[GT=TAX](gt=tax]

yes?)
             LONGITUDE: 0.04W(-0.04) to 0.04W(360)
             LATITUDE: 90S to 90N
             Z:  N/A
             T: 0.5 to 50.5
             E:  N/A
             F:  N/A
             DATA SET: /home/users/tmap/ferret/linux/fer_dsets/data/etopo5.cdf
 
 Total # of data points: 46677600  (4320*2161*1*50*1*1)
 # flagged as bad  data: 46651585
 Minimum value: -10376
 Maximum value: -7000
 Mean    value: -7722.8 (unweighted average)
 Standard deviation: 630.84


! should be
 Total # of data points: 466776000 (4320*2161*1*50*1*1)
 # flagged as bad  data: 466515850

```

 

Migrated-From: http://dunkel.pmel.noaa.gov/trac/ferret/ticket/2148

**Comment by karlmsmith** [comment]
**Comment by ansley.b.manke on 5 Mar 2014 17:59 UTC**
Fixed in var_stat.F. We compute NGOOD, NBAD, NTOT points.  Then NTOT and NBAD get formatted into output strings with calls to LEFINT.  Inside LEFINT, the number is written to a string using an integer format, and blanks removed to left-justify the result. Inside LEFINT, everything's done with a max of 16 digits, so that's all good.

In var_stat, LEFINT was declared as only CHARACTER*8, and that's where the truncation happened.

**Comment by ngd** [comment]
Sorry to bother you, would you mind not using the @ syntax in these messages, everytime you write @ngd it sends me an email.
