### ISSUE TITLE
USE/ORDER=<perm> has bugs when dataset contains mixed dimension variables

### ISSUE THREAD

**Issue by karlmsmith** [NOAA-PMEL/Ferret#1510]
**Reported by steven.c.hankin on 3 Mar 2015 00:42 UTC**
In the attached 3 datasets the time dimension is not associated with an axis.  The result is that Ferret has no way to know its intended orientation.  So when the USE command is used on any of these datasets the L axis is mapped to K or even the I axis.

To the rescue USE/ORDER=TF straightens out the data set order_tf_variable.nc, which contains a 2D variable TIME2D.
Similarly USE/ORDER=XYTF straightens out the data set order_xytf_variable.nc, which contains a 4D variable.

However, when these two variables are placed into a single dataset, order_mixed.nc, neither /ORDER=TF nor /ORDER=XYTF gets the dataset to work correctly.

At this point I have set the priority of this ticket as "low", on the grounds that full support for uaxiliary variables may reduce the cases where /ORDER= is needed even lower than it already is.

Note that if the variable TIME2D were renamed, so that it matched the dimension name TIME, the misbehavior would disappear.

```
yes? use order_tf_variable.nc, order_xytf_variable.nc, order_mixed.nc
yes? SHOW DATA
     currently SET data sets:
    1> ./order_tf_variable.nc
 name     title                             I         J         K         L         M         N
 TIME2D   Forecast time for ForecastModel  1:65      ...       ...       ...       ...       1:3
 
    2> ./order_xytf_variable.nc
 name     title                             I         J         K         L         M         N
 DLWRFSFC net downward longwave radiation  1:10      1:5       1:65      ...       ...       1:3
 
    3> ./order_mixed.nc  (default)
 name     title                             I         J         K         L         M         N
 TIME2D   Forecast time for ForecastModel  ...       ...       1:65      ...       ...       1:3
 DLWRFSFC net downward longwave radiation  1:10      1:5       1:65      ...       ...       1:3
```

Now /ORDER= to the rescue:

```
yes? use/order=tf order_tf_variable.nc
yes? show data
     currently SET data sets:
    1> ./order_tf_variable.nc  (default)
 name     title                             I         J         K         L         M         N
 TIME2D   Forecast time for ForecastModel  ...       ...       ...       1:65      ...       1:3
 
yes? use/order=xytf order_xytf_variable.nc
yes? show data
     currently SET data sets:
    1> ./order_tf_variable.nc
 name     title                             I         J         K         L         M         N
 TIME2D   Forecast time for ForecastModel  ...       ...       ...       1:65      ...       1:3
 
    2> ./order_xytf_variable.nc  (default)
 name     title                             I         J         K         L         M         N
 DLWRFSFC net downward longwave radiation  1:10      1:5       ...       1:65      ...       1:3
```

Now Ferret's problem on the dataset with mixed dimensions

```
yes? use/order=tf order_mixed.nc 
           *** NOTE: Axis RUN marked as FI
           *** NOTE: but it has different directions in grids. Axes in grids may be inconsistent.
yes? show data
     currently SET data sets:
    1> ./order_mixed.nc  (default)
 name     title                             I         J         K         L         M         N
 TIME2D   Forecast time for ForecastModel  1:65      1:3       ...       ...       ...       ...
 DLWRFSFC net downward longwave radiation  1:65      1:3       ...       1:10      ...       1:5
```

and similarly

```
yes? use/order=xytf order_mixed.nc
           *** NOTE: Axis RUN marked as FI
           *** NOTE: but it has different directions in grids. Axes in grids may be inconsistent.
           *** NOTE:
           *** NOTE: Could not adjust grid for variable TIME2D
           *** NOTE: Axes in grids may be inconsistent.
yes? show data
     currently SET data sets:
    1> ./order_mixed.nc  (default)
 name     title                             I         J         K         L         M         N
 TIME2D   Forecast time for ForecastModel  1:65      1:3       ...       ...       ...       ...
 DLWRFSFC net downward longwave radiation  1:10      1:5       ...       1:65      ...       1:3

```

Migrated-From: http://dunkel.pmel.noaa.gov/trac/ferret/ticket/2238

**Comment by karlmsmith** [comment]
**Attachment from steven.c.hankin on 3 Mar 2015 00:43 UTC**
netCDF files that illustrate the problem
REPLACE THIS TEXT WITH UPLOADED FILE ./attachments/TRAC_2238_GIT_1510/order_xytf_variable.nc

**Comment by karlmsmith** [comment]
**Attachment from steven.c.hankin on 3 Mar 2015 00:43 UTC**

REPLACE THIS TEXT WITH UPLOADED FILE ./attachments/TRAC_2238_GIT_1510/order_tf_variable.nc

**Comment by karlmsmith** [comment]
**Attachment from steven.c.hankin on 3 Mar 2015 00:44 UTC**

REPLACE THIS TEXT WITH UPLOADED FILE ./attachments/TRAC_2238_GIT_1510/order_mixed.nc

**Comment by karlmsmith** [comment]
**Attachment from steven.c.hankin on 3 Mar 2015 00:50 UTC**
journal script to demonstrate error
REPLACE THIS TEXT WITH UPLOADED FILE ./attachments/TRAC_2238_GIT_1510/err_order_equals.jnl

**Comment by AnsleyManke** [comment]
The datasets open correctly with Ferret v7.5 with no need for USE/ORDER=

USE/ORDER= still works for the datasets where all the variables are one shape but it doesn't give us a way to say what to do when one variable is T-F and another is X-Y-T-F.
