### ISSUE TITLE
users guide to describe SHOW DATA/FILES for aggregations

### ISSUE THREAD

**Issue by karlmsmith** [NOAA-PMEL/Ferret#1610]
**Reported by steven.c.hankin on 16 Dec 2015 19:37 UTC**
SHOW DATA/FILES now shows the member datasets for E and F aggregations, as well as for T (MC).  This should presumably be mentioned under SHOW DATA/FILES reference and under general discussions of aggregation

Migrated-From: http://dunkel.pmel.noaa.gov/trac/ferret/ticket/2338

**Comment by AnsleyManke** [comment]
obsolete.  SHOW DATA/MEMBERS is the command, and it's in the docs.
