### ISSUE TITLE
@IIN regridding transformation for arbitrary indefinite integrals, and function to return axis edges

### ISSUE THREAD

**Issue by karlmsmith** [NOAA-PMEL/Ferret#1618]
**Reported by @AndrewWittenberg on 30 Dec 2015 21:11 UTC**
Plot a variable and its indefinite integral:

```
 	NOAA/PMEL TMAP
 	FERRET v6.961 (beta)
 	Linux 2.6.32-573.8.1.el6.x86_64 64-bit - 12/09/15
 	30-Dec-15 15:30     

yes? def ax/edge/x=0:10:1 xax
yes? let a = mod(.5+x[gx=xax],2)
yes? ppl cross 1; plot/step=con/vl=-1:6:1/hl=-1:10:1/grat=dash/col=1/thick=2 a
yes? let a_iin = a[x=@iin]
yes? plot/ov/line/sym=2/si=.1/col=2/thick=2 a_iin
```

The problem, as noted at

http://ferret.pmel.noaa.gov/Ferret/documentation/users-guide/variables-xpressions/XPRESSIONS#_VPINDEXENTRY_435

is that the integral result is shifted a half-cell down from where it should be.  Because the full cell is being integrated, the result really ought to sit at the '''upper edge''' of the cell, not the cell center.

Fixing this takes some work, and lots of Ferret knowledge:

```
let xlo = xboxlo[gx=a]
def ax/x xax_edges = xcat(xlo[i=1], xboxhi[gx=a])
let a_iin_edges = a_iin[gx=xax_edges@asn]
let a_int = IF i[gx=xax_edges] EQ 1 THEN 0 ELSE a_iin_edges[x=@shf:-1]
plot/ov/line/sym=28/si=.1/col=3/thick=2 a_int
```

So defining the integral requires two intermediate variables (A_IIN and A_IIN_EDGES) as well as an intermediate axis.  This is messy when one needs a lot of integrals, e.g. when integrating lots of heat budget tendency terms in time to recreate the evolution of ocean temperature.  The intermediate variables must remain defined until all evaluations are done, and then must cleaned up afterward.

To simplify this, I'd suggest two enhancements:

1) Functions to return the N+1 axis edges of a variable:
```
XAX_EDGES(A)
YAX_EDGES(A)
...
```
The result would be on a new axis with N+1 points, and the data values would be identical to the coordinate values.  (I had at first considered suggesting a special variable like XBOX_EDGES[gx=a], but then realized it wouldn't actually share the N-point axis of A.)  The advantage of having the result on a new temporary axis (as opposed to an ABSTRACT axis) will be apparent in the next paragraph.

2) A `@IIN` regridding transformation:
```
let result = integrand[gx=target@iin]
```
The result would be the indefinite integral of INTEGRAND, evaluated at the coordinates of the TARGET axis.  The result at the lowest coordinate value, RESULT[i=1], would always be exactly zero, since there would have been no area integrated up to that point.  If XVAL=X[gx=TARGET] are the x-coordinate values of TARGET, then RESULT[i=2] would be the integral from XVAL[i=1:2]; RESULT[i=3] the integral from XVAL[i=1:3], etc.

Presumably this transformation could borrow heavily from the `@AVE` regridding method; just integrate between TARGET cell '''coordinates''' (placing the result at the upper coordinate) rather than TARGET cell '''edges''', and don't divide by the weight.

----

With those two additions, the following lines

```
let xlo = xboxlo[gx=a]
def ax/x xax_edges = xcat(xlo[i=1], xboxhi[gx=a])
let a_iin_edges = a_iin[gx=xax_edges@asn]
let a_int = IF i[gx=xax_edges] EQ 1 THEN 0 ELSE a_iin_edges[x=@shf:-1]
```

would be replaced by

```
let a_int = a[gx=xax_edges(a)@iin]
```

Migrated-From: http://dunkel.pmel.noaa.gov/trac/ferret/ticket/2346

**Comment by karlmsmith** [comment]
**Comment by steven.c.hankin on 30 Dec 2015 22:10 UTC**
The awkwardness of @IIN has been there forever.  Not good, I agree.

The idea of @IIN as a regridding transformation has a lot of appeal.  It (potentially) addresses the 1/2 grid cell offset problem without the need to invent a lot of new machinery.   It allows you a very natural way to define the zero point for the integration as a value different than (say) the edge point of a plot. And it maps naturally onto staggered model coordinate systems.

Other (less attractive?) possibilities might include:
   o a new transformation that behaves like @iin except that it subtracts off the starting 1/2 grid cell -- say "@IIN2"
   o an optional argument for the @IIN transformation to indicate where in the grid cell the integration represents:  @IIN:0, @iin:.5, @iin:1 being the integral at the start, midpoint or end of each cell, respectively (current behavior is "@iin:1").Maybe @iin:pt, too: the integration value at the location of the grid point.

All of the above need to be thought through for *irregular* (unequal-spaced) axes, too.

If this new functionality existed, would the other complexities still be necessary?  For example the need to return an "edges" object of length N+1.  (The CF method of using an Nx2 representation has proven smoother, even though it opens a door that we'd rather keep closed to dis-contiguous and even overlapping grid cells.)

**Comment by karlmsmith** [comment]
**Comment by andrew.wittenberg on 31 Dec 2015 00:32 UTC**
The first idea you mention that retains same axis (@IIN2 and @IIN:pt) would be useful.  Under my proposed syntax, this could be achieved as:

```
a[not sure how we'd use something like @IIN:f, where f is the fraction of the cell to integrate up to.  But note that this can already be done inline with:

```
a[x=@iin](gx=a@iin]
```

I'm) - (1-f)*a[of these would work fine with irregular axes, and integrating across a missing point would set all subsequent integrals to missing.  (There's a small wrinkle for things like ```a[x=x1:x2@iin](x=@wgt]*a
```

All)``` where the integration may start and end partway through a cell; here the interpretation would be that f is the fraction of the way through those partial end-cells, which would work well for f=0 and f=1.  I'm not sure what the right approach would be for fractional f in such cases.)

The motivation for my proposed syntax is getting integrals onto a '''new''' axis, in a concise way.

E.g. when we're integrating a heat budget in time, the cells contain '''time-average''' heating rates (Kelvins per day).  So say we have a monthly-mean heating rate for January, with cell bounds at midnight 1-Jan and midnight 1-Feb, saved out from our ocean model.  The only thing we know is that the temperature change across that full month was '''exactly''' the integral of the average heating rate.  We can't know the temperature at 15-Jan, since the heating rate might have been fluctuating and we didn't save that info (i.e. the average heating from 1-Jan to 15-Jan).  The only thing well-defined is the temperature at the '''edges''' of the heating cells.

So naturally we'd like to do the integral across the full cell, and have the temperature show up at 1-Jan, 1-Feb, etc. The only way to do that (such that the axis metadata is consistent with the data) is to define a new axis for the result.  We could do that explicitly with:

```
let xlo = xboxlo[ax/x xax_edges = xcat(xlo[i=1](gx=a]
def), xboxhi[then using syntax (2),

```
let a_int = a[gx=xax_edges@iin](gx=a])
```

and)
```

Of if we had syntax (1) that returned an edges-axis, we'd have my suggested inline solution:

```
let a_int = a[that the lowermost point of an @iin regridding would '''always''' be assigned a value of zero (or missing, if A was missing there).  That way it'd be trivial to start the integral from an arbitrary initial condition:

```
let a_int = initial_condition + a[gx=xax_edges(a)@iin](gx=xax_edges(a)@iin]
```

Note)
```

The proposed @IIN regridding would also enable more general integration across multiple cells -- e.g. finding the temperature change across whole-year leaps, given only monthly-mean heating rates.

**Comment by karlmsmith** [comment]
**Comment by steven.c.hankin on 31 Dec 2015 19:32 UTC**
Thanks for the clear explanation of the integration use case -- the edge-to-edge integral over each cell, correctly located.  Still, I wish we could sit down together with a chalk board to really clarify how to get a very good result (if not necessarily 'the best') with the smallest effort and disruption.

I think we have some good proposals here.  The decisions to be made will be over weighing the cost/benefits of the alternatives.  The area of my unease with the XAX_EDGES concept you have above is that it generates an axis of length N+1. The virtue of the N+1 style of solution, is that the resultant integral includes a comforting zero value at I=1.  The downside is that it requires new machinery and my Spidey senses tell me this is going to create conformability problems (N versus N+1) before we're done with it.

Here's a cleaned up summary of the two concrete "@IIN" proposals so far.

'''Proposal 1: @IIN as a regridding operator:'''
Yes - insist that the starting point for integration be the location of the first grid point on the target axis (and therefore a value of zero).  (On further thought, implementation of this regridding transform may get quite messy.  The user-requested region may not include the first point of the target axis, so Ferret regridding will need new logic and performance inefficiencies to force the integration calculation to start at I=1.  Alternatively, the parser could insist that X=lo:hi limits are always included with GX=@IIN.)

'''Proposal 2: @IINUP and @IINPT as two new transformations:'''
   o @IIN to issue a warning: ''@IIN is deprecated.  Use @IINUP for same result or @IINPT for correct centering''
   o @IINPT gives the integration values at the grid points.  Thus for 
```
LET myint=myvar[   , if tlo lies exactly on the grid point, the value of myint[L=1](t=tlo:thi@IINPT]
```
) is 0.0.  If tlo lies between the lower edge of the cell and the grid point, myint[is positive.  If tlo lies between the grid point and the upper edge of the cell, myint[L=1](L=1]) will be a small negative value.
   o @IINUP gives the integration values at the upped edge of the grid cells.  This would match the current behavior of @IIN, I think.

Proposal 1 addresses the use case you articulated, but does not address the somewhat messy syntax needed to define the desired target axis.   For that you have proposed a new syntax (with attendant increase in scope)

Proposal 2 addresses the "classic" use case of easy-to-understand indefinite integration, but does not address your use case because you want the edge integral results that sit on the edge locations.

The ideal, simple answer would be if @IINUP could return its result on a 1/2 cell-shifted axis.  Unfortunately, the @ transformations don't know how to do this.  Grid-changing functions, however, do know how to do this.  So here's proposal 3.

'''Proposal 3 -- grid-changing function to perform edge-to-edge indefinite integral'''
   o let a_int = IIN_XEDGE(a, X0)
IIN_XEDGE would synthesize a new X axis with points located at the upper cell edge positions of the X axis of "a".  X0 would give the starting point of the integration.  (Negative integral results can result.)

**Comment by karlmsmith** [comment]
**Comment by andrew.wittenberg on 31 Dec 2015 21:26 UTC**
Amending Proposal 1, how about this:

``` 
let myint = source[integral starts (with value 0) at x=x0 if it is provided; otherwise it starts at the lower edge of the active region; otherwise it starts at the lowermost edge of SOURCE.  Target points below x0 (or the region) would be reverse-integrated, with sign flipped.  Note that values below the active region would only be requested if daughter-variables required a halo -- e.g. for interpolation or smoothing to the edges of the region.

Then Proposal 2 (@IINPT) is handled as a special case:

```
let myint = source[gx=source@IIN:x0](gx=target@IIN:x0]
```

The)
``` 

Proposal 3 is less general and flexible than Proposal 1, since it restricts the regridding to the edges of A, and the integration starting point couldn't change if the region changed.  Instead we could use the above to do:

```
let xlo = xboxlo[xhi = xboxhi[gx=a](gx=a]
let)
def ax/x xax_hi = xhi
let a_int = a[to get precisely what I want:

```
def ax/x xax_edges = xcat(xlo[i=1](gx=xax_hi@iin:`xlo[i=1]`]
```

or), xhi)
let a_int = a[gx=xax_edges@iin:`xlo[i=1]`]
``` 

Regarding the XAX_EDGES(A) function idea -- this is largely cosmetic, I can drop it if it's too thorny.

**Comment by karlmsmith** [comment]
**Comment by steven.c.hankin on 31 Dec 2015 23:46 UTC**
Hi Andrew,

Before delving further into the details of these proposals, I'd like to make sure that what seems like the simplest 'hack' is also on the table.  Best self-described by a Ferret session:

```
define axis/x=161:179:2 xax_even
show axis/x xax_even
 name       axis              # pts   start                end
 XAX_EVEN  X                   10 r   161                  179
   Axis span (to cell edges) = 20
 
       I     X                   XBOX      XBOXLO
       1>  161                   2          160
       2>  163                   2          162
       3>  165                   2          164
       4>  167                   2          166
       5>  169                   2          168
       6>  171                   2          170
       7>  173                   2          172
       8>  175                   2          174
       9>  177                   2          176
      10>  179                   2          178
 
let myvar = I[ ! for easy mental calculations
 
let cell_width = 2
list/x=161:179 myvar, myvar*cell_width
             X: 161 to 179
 Column  1: MYVAR is I[GX=XAX_EVEN](gx=xax_even])
 Column  2: EX#2 is MYVAR*CELL_WIDTH
            MYVAR   EX#2
161   /  1:   1.00   2.00
163   /  2:   2.00   4.00
165   /  3:   3.00   6.00
167   /  4:   4.00   8.00
169   /  5:   5.00  10.00
171   /  6:   6.00  12.00
173   /  7:   7.00  14.00
175   /  8:   8.00  16.00
177   /  9:   9.00  18.00
179   / 10:  10.00  20.00
 
! the current @IIN isn't "wrong", but its result is located at the grid point
! when it really should be located at the upper edge of each grid cell
let myvar_iin = myvar[myvar_iin
             VARIABLE : MYVAR[X=160:180@IIN](x=160:180@iin]
list)
             SUBSET   : 10 points (X)
 161   /  1:    2.0
 163   /  2:    6.0
 165   /  3:   12.0
 167   /  4:   20.0
 169   /  5:   30.0
 171   /  6:   42.0
 173   /  7:   56.0
 175   /  8:   72.0
 177   /  9:   90.0
 179   / 10:  110.0
 
! define a new axis with points at the upper grid cell bounds
define axis/x xax_odd = xboxhi[
! and force-shift the @iin results to these grid points
let myvar_iin_at_edge = myvar_iin[gx=xax_odd@asn](gx=xax_even]
)
list myvar_iin_at_edge[            VARIABLE : MYVAR_IIN[GX=XAX_ODD@ASN](x=161:180]
)
             SUBSET   : 10 points (X)
 162   /  1:    2.0
 164   /  2:    6.0
 166   /  3:   12.0
 168   /  4:   20.0
 170   /  5:   30.0
 172   /  6:   42.0
 174   /  7:   56.0
 176   /  8:   72.0
 178   /  9:   90.0
 180   / 10:  110.0
```

Just double checking that you have considered this approach ...

----
OK -- discussing the proposals:

Proposal #1 in the modified form 
```
let myint = source[gx=target@IIN:x0]
```
still requires a new syntax (regridding transforms that accept arguments).  It may not seem like a big effort but it means
  - additions to data structures
  - additions to parser
  - new machinery to set default arguments
  - modifications to memory management checking for cache hits
And by allowing the argument to be a lower value than the start of the requested axis, that means that the range of component data needed to evaluate the result becomes dependent on the argument value, which means changes in the delayed mode evaluation logic, too.  These steps are in addition to implementing the mathematical logic (overwhelmingly the simple part).  You see how a little change cascades ...  So while not ruling it out, it has some initial weight against it from a cost/benefit perspective.

About Proposal 2 -- we may have a misunderstanding.  I didn't intend Proposal 2 to be a regridding transformation.  It is a simple, non-compressing transformation, like the current @IIN.  I'm tempted to put Proposal 2 high on the toDo list, because @IIN has always been problematic.  Unfortunately I don't think it addresses the particular use case you've identified.

I agree that Proposal 3 is less general (and not very pretty).  On the other hand it is a relatively small amount of work.  The lack of generality didn't seem like a problem to me (yet?), because I have not been able to think of any use cases where we want indefinite integrals to be evaluated at places other than the grid points or grid edges of the native grid.  Can you suggest such a use case?

**Comment by karlmsmith** [comment]
**Comment by andrew.wittenberg on 1 Jan 2016 05:47 UTC**
Yep -- see my initial report, 2nd box.  And a use case for general regridding was mentioned at the bottom of my comment:2.

I understood what you meant by Proposal 2; I was just demonstrating that it'd be a special case of Proposal 1, with "regridding" to the same grid (i.e., not actually regridding!).  So it could be handled differently internally if need be, without adding syntax beyond Proposal 1.

Maybe we can sidestep the implementation difficulties via a scaled-back Proposal 1, without the argument:

```
let myint = source[integral starts (with value 0) at the lower edge of the active region; otherwise it starts at the lowermost edge of SOURCE. Target points below this would be reverse-integrated, with sign flipped (these would only be requested if daughter-variables required a halo -- e.g. for interpolation or smoothing to the edges of the region).

Then we'd get the x0 behavior with

```
let myint_x0 = myint - myint[x=`x0`](gx=target@IIN]
```

The)
```

**Comment by karlmsmith** [comment]
**Comment by steven.c.hankin on 4 Jan 2016 18:14 UTC**
ok.  I'd like to offer a "synthesis proposal" -- combining the above into something that I think (hope) will meet all needs.
  1. we implement Proposal 2 (i.e new @IINPT and @IINUP).  When coding it we must ensure that if the lower bound of the integration lies exactly on the grid point (for @IINPT) or cell edge (for @IINUP), a value=0 point will be included as the starting point of the integration.
  2. we tweak the documentation of @IINUP (see Method 2 of current @IIN documentation [http://ferret.pmel.noaa.gov/Ferret/documentation/users-guide/variables-xpressions/XPRESSIONS#_VPINDEXENTRY_437]) to show how easy it is to create the shifted axis using *BOXHI.  (I find the use of *BOXHI as a way to create a half-cell shifted axis and @ASN to assign the result to that axis to be quite intuitive -- hoping it would be accessible to Ferreters of moderate skill.)

The result should be that the most common use of @IIN (with deprecation warning message guiding the user to the use of the new @IINPT) will be a fully-correct answer and easy to understand.  And for those who need the integration results to be at the cell edges (as in your use case), it is a simple and well-documented matter to obtain the coordinate-shifted result, including a zero-valued point at the start of integration.

**Comment by karlmsmith** [comment]
**Comment by andrew.wittenberg on 5 Jan 2016 00:23 UTC**
I'd suggest @IINHI instead of @IINUP, both to prevent confusion with DEPTH axes where "up" is the opposite of "hi", and for consistency with the HI used elsewhere (e.g. in the XBOXHI special variable).  With that, Proposal 2 would be fine, it'd help prevent naive misuse of integral results, and I'm sure I'd use it sometime.

It doesn't address what I'd proposed in the original request, which was for a way to do off-source-grid integrals directly without defining several intermediate variables and using XCAT().  In my present application, I'm doing many tens or even hundreds of these integrals, so that's an awful lot of intermediate variables to keep track of, for later cleaning up.  But that's ok -- you're allowed to say "hell no" to me every now and then. :-)

**Comment by karlmsmith** [comment]
**Attachment from andrew.wittenberg on 30 Dec 2015 21:11 UTC**
The resulting plot.
REPLACE THIS TEXT WITH UPLOADED FILE ./attachments/TRAC_2346_GIT_1618/plot.gif

**Comment by AnsleyManke** [comment]
I've added a @IIN regridding transformation so this can work -mostly- as described in the original post. We don't have a good mechanism to automatically define the new axis, either within the transformation framework or even with an external function (In external functions we CAN define an axis based on coordinates of the arguments, but only a regularly-spaced one.) 

With a new function BOX_EDGES and DEFINE AXIS/LIKE=  to define the new axis, the example looks like this:

```

yes? define axis/edge/x=0:10:1 aline
yes? let a = mod(.5+x[gx=aline],2)

yes? define axis/x/like=`a,return=xaxis` aline_edges = box_edges(a)
yes? let a_iin_regrid =  a[gx=aline_edges@iin]

yes? plot/step=con/vl=-1:6:1/hl=-1:11:1/grat=dash/thic=3 a
yes? let a_iin = a[x=@iin]

yes? plot/ov/line/sym=2/siz=.1/color=red/thick a_iin

yes? let a_iin_regrid =  a[gx=aline_edges@iin]
yes? plot/ov/line/sym=2/siz=.1/col=green/thic=2 a_iin_regrid

```

and the plot matches what's above,
![iin](https://user-images.githubusercontent.com/5122690/36761637-dcb0b506-1bd4-11e8-927d-a2a8bdd57909.png)




We can revisit this if some of the ideas in the Nov 23 comment, IINUP and IINDN seem appealing, but I'll close this for now.

**Comment by AndrewWittenberg** [comment]
Thanks very much, this will certainly consolidate many lines of code in scripts, and prevent integration mistakes!  Definitely add this to the docs & FAQs on integration.

If there were a mechanism to auto-define aline_edges on-the-fly, it'd be helpful to eliminate "user-defined auxiliary axes."  But... BOX_EDGES() and DEFINE AXIS/LIKE do get us nearly all the way there.  And the explicit definition of aline_edges does eliminate any ambiguity regarding the name of the result axis, and eliminates the need for "Ferret-defined auxiliary axes."  So I'm satisfied -- thank you again.

**Comment by AndrewWittenberg** [comment]
From Ch. 3, Sec. 2.4.1 of the user's guide:

> When calculating integrals and derivatives (@IIN, @DIN, @DDC, @DDF, and @DDB) Ferret attempts to use standardized units for the grid coordinates. If the underlying axis is in a known unit of length Ferret converts grid box lengths to meters. If the underlying axis is in a known unit of time Ferret converts grid box lengths to seconds. If the underlying axis is degrees of longitude a factor of COSINE (latitude) is applied to the grid box lengths in meters.

But the @IIN **regridding transformation** appears to use something different from standardized units. 
 Here's an example, where we take a derivative and then integrate, trying to recover the original field:

```
 	NOAA/PMEL TMAP
 	FERRET v7.32 (optimized)
 	Linux 2.6.32-696.20.1.el6.x86_64 64-bit - 03/19/18
 	24-Mar-18 16:01     

yes? can mode verify
yes? use monthly_navy_winds
yes? set reg/x=140w/y=0
yes? let a = uwnd
yes? def ax/t/edge/like=`a,r=taxis`/t0="`a,r=t0`" tax_deriv = t[gt=a]
yes? let a_ddf = a[t=@ddf]
yes? let da_dt = a_ddf[gt=tax_deriv@asn]
yes? let da_dt_iin = a[l=1] + 3600*da_dt[gt=a@iin]
yes? plot/sym=27 a; plot/ov/step=con da_dt_iin
```

It works great, as long as we have that factor of 3600 in the 2nd-to-last line!

That's the number of seconds in an hour...  The derivative appears to be dividing by the standardized units of seconds, while the integral is multiplying by intervals in hours (the underlying axis units) rather than seconds.

**Comment by AndrewWittenberg** [comment]
Further problems with the new `@IIN` regridding:

```
 	NOAA/PMEL TMAP
 	FERRET v7.32 (optimized)
 	Linux 2.6.32-696.20.1.el6.x86_64 64-bit - 03/19/18
 	24-Mar-18 15:55     

yes? def ax/edge/t=1-jan-0001:1-jan-0004:365/unit=day/cal=noleap tax
yes? let one = 1 + 0*t[gt=tax]
yes? list one, one[t=@iin], one[gt=tax@iin]
             TIME: 01-JAN-0001 00:00 to 01-JAN-0004 00:00 NOLEAP
 Column  1: ONE is 1 + 0*T[GT=TAX]
 Column  2: ONE[T=@IIN] is 1 + 0*T[GT=TAX] (indef. integ. on T)
 Column  3: ONE is 1 + 0*T[GT=TAX]
                ONE      ONE      ONE
JUL-0001 / 1:  1.000  3.154E+07  1.000
JUL-0002 / 2:  1.000  6.307E+07  1.000
JUL-0003 / 3:  1.000  9.461E+07  1.000
```

Ferret doesn't even appear to be applying the `@IIN` transformation in Column 3!  Look at what it's listing: `Column  3: ONE is 1 + 0*T[GT=TAX]`.  No `@IIN` transformation in sight!

**Comment by AnsleyManke** [comment]
This is fixed.  The code applying world-coordinate units was overlooked in the initial implementation of this regridding transformation.

For the example just above which asks for regridding to the source axis, it indeed is doing nothing. All regridding transformations behave this way: if we ask to regrid to the same axis, that's detected as no-need-to-do-anything, and the result is just the untransformed expression.  So this is an artifact of implementing this version of IIN as a regridding transform.  Regridding to a new, identical axis does work.  Perhaps ideally a NOTE could be written.  At the least this needs documenting.

With the corrections so that the result is returned with units in world coordinates:


```
yes? def ax/edge/t=1-jan-0001:1-jan-0004:365/unit=day/cal=noleap tax
yes? let one = 1 + 0*t[gt=tax]

yes? list one, one[t=@iin], one[gt=tax@iin]
             TIME: 01-JAN-0001 00:00 to 01-JAN-0004 00:00 NOLEAP
 Column  1: ONE is 1 + 0*T[GT=TAX]
 Column  2: ONE[T=@IIN] is 1 + 0*T[GT=TAX] (indef. integ. on T)
 Column  3: ONE is 1 + 0*T[GT=TAX]
                ONE      ONE      ONE
JUL-0001 / 1:  1.000  3.154E+07  1.000
JUL-0002 / 2:  1.000  6.307E+07  1.000
JUL-0003 / 3:  1.000  9.461E+07  1.000

yes? def ax/edge/t=1-jan-0001:1-jan-0004:365/unit=day/cal=noleap tax2

yes? list  one[gt=tax2@iin]
             VARIABLE : 1 + 0*T[GT=TAX]
                        regrid: 365 day on T@IIN
             SUBSET   : 3 points (TIME)
             CALENDAR : NOLEAP
 JUL-0001 / 1:  0.000E+00
 JUL-0002 / 2:  1.577E+07
 JUL-0003 / 3:  3.154E+07
```

**Comment by AndrewWittenberg** [comment]
I hadn't realized that a regrid to the same axis was a no-op... that seems appropriate for most of the regridding transforms, but certainly not all of them.  Examples where it's not appropriate: `@var`, `@ngd`, `@modvar`, `@modngd`, `@modnbd`, `@nbin`, `@iin`.  I'll enter this in a separate ticket.

**Comment by AnsleyManke** [comment]
For the IIN regridding transformation I am having the code insist that the destination axis is the source axis or its coordinates are the cell edges of the source axis.  Because the integration is on the source axis, and the result placed on the destination axis in a specified way, I think this is the only sensible meaning of the operation.  There could probably be some details with the first and last grid cell being partial cells, if needed, but for now the axes must line up in this way.

**Comment by AndrewWittenberg** [comment]
I'd prefer not to have such restrictions... The result ought to be defined for all destination axes, where we interpret the source data as having a constant value over each source cell.

So say we have heating rates on a monthly source axis with edges at 1-Jan, 1-Feb, 1-Mar, etc.  Then if we want the integral on a daily destination axis, that's fine: the result would look like a series of linear ramps, with slopes that change at 1-Jan, 1-Feb, etc.

**Comment by AnsleyManke** [comment]
ok - of course this can be generalized.

**Comment by AnsleyManke** [comment]
This is finished. 

 A regridding to the source axis computes the result at the grid coordinates, that is the result at the first coordinate is the value weighted by the lower half of the grid cell; the final value is the integral from the bottom of the first grid cell to the coordinate location of the last cell.

Likewise for any axis; the integration is the weighted sum of the source variable from the start of the first cell to each coordinate value on the destination axis.

Units are handled as for other regridding: time units are translated. Results are expressed using units of hours for time axes or meters for lon/lat axes.  

Interestingly, I find that for regridding transformations including linear and average regridding, etc, time and lon/lat axes are handled correctly. But when the axes have other translatable units such as meters, km, miles, those are NOT translated, and no check is even done to see if the units of the destination axis match the source axis.  This will get its own ticket.  For IIN regridding, I check whether units match, and (for now) a regridding from an axis in km to an axis in miles results in an error.
