### ISSUE TITLE
add .agg to list of recognized dataset extensions

### ISSUE THREAD

**Issue by karlmsmith** [NOAA-PMEL/Ferret#1651]
**Reported by @AndrewWittenberg on 7 Mar 2016 21:26 UTC**
For an aggregation file "my.agg" (for which "use" translates to "go"), the following should be made to work by adding .agg at the end of the list of recognized extensions:

```
 	NOAA/PMEL TMAP
 	FERRET v6.97 (beta/opt)
 	Linux 2.6.32-573.18.1.el6.x86_64 64-bit - 03/04/16
 	 7-Mar-16 16:23     

yes? use my
 **TMAP ERR: non-existent or not on line
             Searched $FER_DESCR and $FER_DATA for des2(.nc ,.cdf,.des)
```

Migrated-From: http://dunkel.pmel.noaa.gov/trac/ferret/ticket/2379

**Comment by karlmsmith** [comment]
**Comment by steven.c.hankin on 7 Mar 2016 23:17 UTC**
This comes as no surprise, I'm afraid.  I'm sorry that I evidently failed to outline this detail as a behavior that we knew in advance would come along with the 'hack' we used to disguise a journal file as a dataset descriptor.

It is certainly possible to hack around the hack.  Is it important enough that we should make it a task to do so?

**Comment by karlmsmith** [comment]
**Comment by andrew.wittenberg on 8 Mar 2016 17:38 UTC**
Yes, I think so -- though with low priority...

**Comment by AnsleyManke** [comment]
This "use my.agg" syntax to define an aggregation in a script and then run the script to define the aggregation via a "use" command, grew out of an email discussion, and is not discussed in any tickets, not documented, and is not tested in our benchmark scripts.  

Andrew, are you making use of this feature?  If so I will capture what's in the email thread in a ticket, along with what seem to be one or two unresolved issues also discussed there.

The portion of the email thread that I have, is Jan 22, 2016 through Feb 16, 2016, with Hankin, Wittenberg, Smith, Manke included, and  has the subject line, "PyFerret Update" or "Re: PyFerret update -- .agg file discussion"

**Comment by AndrewWittenberg** [comment]
Yes, we use this feature.

**Comment by AnsleyManke** [comment]
I've extended Steve's hack, so that

`yes? use my`

will run the script my.agg, found somewhere in the FER_GO paths, and

```
yes? use /home/users/ansley/aggscritps/my_7 
yes?  "/home/users/ansley/fourfiles"
```

will initialize aggregations described in .agg scripts in those directories.

Also added tests for this syntax to the benchmark suite.

**Comment by AndrewWittenberg** [comment]
One trivial addition needed -- if the dataset doesn't exist, then ".agg" should be added to the returned list of items searched for:

```
 	NOAA/PMEL TMAP
 	FERRET v7.41 (optimized)
 	Linux 2.6.32-754.el6.x86_64 64-bit - 07/09/18
 	10-Jul-18 11:02     

yes? use nonexistent
 **TMAP ERR: non-existent or not on line
             Searched $FER_DESCR and $FER_DATA for nonexistent(.nc ,.cdf,.des)
```

Instead this should say:

```
yes? use nonexistent
 **TMAP ERR: non-existent or not on line
             Searched $FER_DESCR and $FER_DATA for nonexistent(.nc ,.cdf,.des,.agg)
```

**Comment by AnsleyManke** [comment]
Yes!

```
        NOAA/PMEL TMAP
        FERRET v7.42 (beta/debug)
        Linux 2.6.32-696.30.1.el6.x86_64 64-bit - 07/10/18
        10-Jul-18 10:37     

yes? use nonexistent
 **TMAP ERR: non-existent or not on line
             Searched $FER_DESCR and $FER_DATA for nonexistent(.nc ,.cdf,.des,.agg)

```
