### ISSUE TITLE
grid limit reached for FMRC & ENSEMBLE aggregation (F then E)

### ISSUE THREAD

**Issue by karlmsmith** [NOAA-PMEL/Ferret#1657]
**Reported by @AndrewWittenberg on 9 Mar 2016 23:58 UTC**
I got the following error when attempting to aggregate 12 ensemble members for 24 starts (NE=12, NF=24):

```
 	NOAA/PMEL TMAP
 	FERRET v6.97 (beta/opt)
 	Linux 2.6.32-573.18.1.el6.x86_64 64-bit - 03/09/16
 	 9-Mar-16 18:35     

 **TMAP ERR: limit on number of grids has been reached
 **ERROR: internal program problem: attListCrptn: AVERAGE_T1
```

where AVERAGE_T1 happens to be a variable in my dataset.  Ferret stopped after dataset 225, which was FMRC 9 of 12, prior to creating the ENSEMBLE.

I can't send the datasets as there are many, many files... but presumably it wouldn't be hard to reproduce this by having Ferret write out a bunch of dummy files.

Migrated-From: http://dunkel.pmel.noaa.gov/trac/ferret/ticket/2385

**Comment by karlmsmith** [comment]
**Comment by steven.c.hankin on 14 Mar 2016 20:52 UTC**
Each file of the agg requires two grids, and there are 288 files, leading to a need for over 500 grids.  The Ferret program limit was set at 500.  Increasing the parameter num_dyn_grids to 5000 has fixed this problem.  Each grid uses about 20 words of storage.  In principle, all of the ensemble members could be sharing identical grid definitions, which would reduce the demand for grids.  I am reluctant to make this change out of (an excess of?) caution -- Ferret has been running a very long time without sharing grid definitions between files. Changes to features like that often lead to unanticipated side-effects.

I will check the changes in soon.  I need first to coordinate with Ansley on one detail that I found while making the change to num_dyn_grids.

**Comment by karlmsmith** [comment]
**Comment by andrew.wittenberg on 15 Apr 2016 16:41 UTC**
This is working great for me now in v6.97beta5 dated 4/14/16.  Thanks!

I'm able to make beautiful plots of the 12-member ensemble stddev over the 2-year course of the 1997-98 El Nino & La Nina.  It took a little while to load the hyperslab out of the files -- a single XY gridpoint (a 3456-element TEF slab) took 30 seconds, but the NINO3 region (2000 spatial gridpoints, a 6.6 million-element XYTEF slab) only took 50 seconds.  So it seems that the main cost is opening the hundreds of files and reading their headers, which might be particularly slow on our archive filesystem.  But once the slab was in cache, all my subsequent operations, regriddings, transformations happened instantly.  

The factor of 10 increase in grid number will now get us up to 19 years of 12-member monthly forecasts, i.e. 1997-present.  '''Any chance that you could give us another doubling, up to 10,000 grids?'''  That way we could do 1978-present, which would suffice for much of our science over the next couple of years.  (Good ENSO observations, and most of our retrospective forecast suites, begin in 1979.)

**Comment by AnsleyManke** [comment]
This is simple enough along with the changes that went into resolvoing #1694.  I have allowed the number of grids to be 10000.
