### ISSUE TITLE
Complete upgrading functions 4d to 6D

### ISSUE THREAD

**Issue by karlmsmith** [NOAA-PMEL/Ferret#1680]
**Reported by @AnsleyManke on 2 May 2016 16:36 UTC**
There's a set of functions that were never converted from 4D to 6D; upgrade them to 6D.  This will eliminate users having to have their own versions that are 6d.  

In addition there are a number of functions not documented in the Users Guide.  

Migrated-From: http://dunkel.pmel.noaa.gov/trac/ferret/ticket/2408

**Comment by karlmsmith** [comment]
**Modified by ansley.b.manke on 11 May 2016 23:15 UTC**

**Comment by karlmsmith** [comment]
Adding @AndrewWittenberg

**Comment by AnsleyManke** [comment]
This is done.
