### ISSUE TITLE
DEFINE VAR/QUIET does nothing

### ISSUE THREAD

**Issue by karlmsmith** [NOAA-PMEL/Ferret#1818]
**Reported by @AnsleyManke on 23 Jun 2017 18:41 UTC**
The documentation says 

> DEFINE VARIABLE/QUIET
> 
> Suppresses message that, by default, tells you when you are redefining an existing variable. 
> This qualifier is useful in command files.

However in all versions of Ferret, there is no message issued when a variable is redefined.  The test for whether LET/QUIET was set is commented out in the earliest code available in SVN, and was removed entirely several years ago. 

Remove this from the documentation. (Do not remove LET/QUIET as a qualifier, as this would break lots of scripts including our own.) Could clean up LET/QUIET from existing scripts.

 

Migrated-From: http://dunkel.pmel.noaa.gov/trac/ferret/ticket/2546

**Comment by AnsleyManke** [comment]
This is done. I left in one sentence saying there used to be a message written which no longer is.
