### ISSUE TITLE
PyFerret STOP on loading color palettes

### ISSUE THREAD

**Issue by karlmsmith** [NOAA-PMEL/Ferret#1836]
**Reported by ansley b manke on 11 Oct 2017 17:02 UTC**
For some combinations of color palettes and color levels, drawing a second color plot causes a STOP in PyFerret,

```
yes? let fcn = 0.5*COS(J[fill/pal=land_sea_values/lev=vc 7000*fcn

yes? fill/pal=ocean_temp_bounds/lev=(-2,35,2)  18/5* fcn
STOP FGD_GSCR: Invalid redfrac
```

In Ferret, this same issue is seen but we just get several gks messages, and the plot is drawn successfully.

```
...
yes? fill/pal=ocean_temp_bounds/lev=(-2,35,2)  18/5* fcn
gsetcolourrep()   96 Colour is outside range [0,1](j=1:100]/30)+SIN(K[k=1:100]/20)
yes?)
gsetcolourrep()   96 Colour is outside range [0,1]
...
```

On starting a color plot, Ferret goes and loads the colors from the palette into data structures and also loads the color levels if they've been set and associates colors from the palette with color levels. Information from the first plot, with 26 distinct color levels is being incorrectly re-used in the setup stages for the second plot which is going to have just 19 color levels.

Migrated-From: http://dunkel.pmel.noaa.gov/trac/ferret/ticket/2564

**Comment by AnsleyManke** [comment]
This was fixed in plt/disp_prep.F
