### ISSUE TITLE
non-gregorian calendar definition lost in descriptor files

### ISSUE THREAD

**Issue by AnsleyManke** [NOAA-PMEL/Ferret#1850]
As reported in this message,
https://www.pmel.noaa.gov/maillists/tmap/ferret_users/fu_2017/msg00713.html

if the descriptor file specifically says the time axis is non-Gregorian calendar time axis, that information is lost and so the date string is wrong.  In addition if the member files have non-Gregorian calendars they are treated as Gregorian.

**Comment by AnsleyManke** [comment]
This is fixed in gt_get_time_axis, used currently only for defining a time axis used by a descriptor file.  The line attributes were not all transferred to the descriptor datset-level time axis being defined.

New tests added.

**Comment by karlmsmith** [comment]
Fix pushed to GitHub
