### ISSUE TITLE
Latest Ferret gives blank thumbnail plots in SOCAT LAS

### ISSUE THREAD

**Issue by karlmsmith** [NOAA-PMEL/Ferret#1852]
Using Ferret v7.3.1 as of 11 Jan (and a version a few days ago), many of the SOCAT LAS thumbnails are blank for MLCE2016 datasets.  These datasets cover about two weeks, so a relatively short time for SOCAT/LAS.  This does not occur for Ferret 7.3 release, so something to do with the recent changes.

The following is a snapshot of some of the thumbnails for MLCE20160625 on my test SOCAT LAS on merlot using Ferret.

<img width="1371" alt="screen shot 2018-01-11 at 2 17 21 pm" src="https://user-images.githubusercontent.com/16406727/34850526-1adb3780-f6db-11e7-8037-eeb573fe008a.png">

**Comment by karlmsmith** [comment]
@AnsleyManke - Using the latest Ferret and LAS scripts, appears this is (almost) fixed.  The only problem observed is when there is no data (all missing values), the plot is not produced (broken image icon in the browser) instead of the usual plot saying no valid data (or whatever it was that was said before).

**Comment by AnsleyManke** [comment]
This is fixed.  I did SVN checkins, merging the fix from the trunk to the socat_latest branch -
