### ISSUE TITLE
PyFerret fonts: CONTOUR label color not reset after previous plot

### ISSUE THREAD

**Issue by AndrewWittenberg** [NOAA-PMEL/Ferret#1857]
In PyFerret when using a non-Hershey font, the color of the contour labels is incorrect when a new CONTOUR is performed in a new viewport, after a CONTOUR in a different viewport.  It looks like the pen color for the contour labels is not getting properly reset for the new plot.

```
 	NOAA/PMEL TMAP
 	PyFerret v7.31 (beta/optim)
 	Linux 2.6.32-696.16.1.el6.x86_64 - 12/27/17
 	30-Jan-18 20:37     

yes? set text/font="arial"
yes? set reg/x=230:290/y=20s:20n/l=1
yes? use coads_climatology

yes? set view left
yes? contour/lev=1d sst
yes? cont/ov/lev=(24) sst

yes? set view right
yes? contour/lev=1d sst
```

See plot below -- the contour labels in the right panel should be black, not red.

![plot](https://user-images.githubusercontent.com/34082818/35600881-3a897cf4-05fe-11e8-81a6-8dcc16d1699c.png)

**Comment by AnsleyManke** [comment]
This is fixed in plotz.F and checked in on the pyFerret branch, with a test added in the benchmarks.

**Comment by karlmsmith** [comment]
The change made the date at the top of this plot change from blue (which was assigned by a SET TEXT /COLOR=BLUE via Python method in bench/pyscripts/testfermethods.py) to black.  The plot was a PDF, but made a PNG of it to more easily show it here.

![testfermethods_fill](https://user-images.githubusercontent.com/16406727/35709071-ccd8af0e-0765-11e8-8e2b-138c0ee43451.png)

**Comment by AnsleyManke** [comment]
Ok this is now working correctly as well.
