### ISSUE TITLE
site_specific.mk missing

### ISSUE THREAD

**Issue by mvhulten** [NOAA-PMEL/Ferret#1865]
`README_build_ferret` tells me to edit `site_specific.mk`, but it is missing.

**Comment by karlmsmith** [comment]
See the bottom of the README.md file (bottom of the GitHub default page for Ferret).  The site_specific.mk files (there are two, one in the root directory and another under external_functions/ef_utility) were renamed in the repository to site_specific.mk.in for the repository.  These are intended to be example configuration files that you rename to site_specific.mk and make your customizations.  By doing this, one person's customizations do not get checked in and overwrite another person's customizations.

Leaving this open to remind us to update the README_build_ferret file.  Apologies that this change did not get into that file.

**Comment by karlmsmith** [comment]
README_build_ferret updated.
