### ISSUE TITLE
Ferret 7.4 binary not portable

### ISSUE THREAD

**Issue by oliviermarti** [NOAA-PMEL/Ferret#1869]
I've just installed Ferret 7.4. I get

```
marti@Spip-~/local/softs/Ferret 👉  ferret
dyld: Library not loaded: /Users/ksmith/.local/opt/gcc/lib/gcc/7/libquadmath.0.dylib
  Referenced from: /Users/marti/local/softs/Ferret/bin/ferret
  Reason: image not found
Abort trap: 6
```

Olivier

**Comment by karlmsmith** [comment]
Apologies for the delay; I didn't see your message until just now.

The MacOSX prebuilt includes a `dylibs` subdirectory with `libquadmath.o.dylib` and `libgcc_s.1.dylib`.  The `ferret_paths.*` scripts now include setting `DYLD_FALLBACK_LIBRARY_PATH` to add `${FER_DIR}/dylibs`.  Make sure you did an `Finstall` using the latest version.  (If you use a symbolic link that points to the directory of the latest version of Ferret, make sure to update that symbolic link *before* running `Finstall`.) Or at the very least, add the section updating `DYLIB_FALLBACK_LIBRARY_PATH` found in the appropriate `bin/ferret_paths_template.*` file.
