### ISSUE TITLE
multi-dimensional average fails to apply partial weights to outermost cells

### ISSUE THREAD

**Issue by AndrewWittenberg** [NOAA-PMEL/Ferret#1880]
I found this while comparing heat content (vertical-mean temperature) between two different models; I was seeing an unexpectedly large difference that was inconsistent with other calculations.  This is urgent since it silently gives wrong results; needs to be fixed right away and distributed to the community, with warnings about the incorrect answers in v7.11-7.4.  It'd be good to add regression tests to catch this as well.

This bug first appears in v7.11, dated 4/19/2017.  (It was not in v7.1, dated 2/16/2017.)  May be related to the new memory management, and/or the fix for #1590.

First create a little 2-d field:

```
 	NOAA/PMEL TMAP
 	FERRET v7.4 (optimized)
 	Linux 2.6.32-696.23.1.el6.x86_64 64-bit - 04/18/18
 	 5-Jul-18 14:06     

yes? can mode verify
yes? def ax/edge/x=0:2:1 xax; def ax/edge/y=0:2:1 yax; let a = x[gx=xax] + y[gy=yax]
yes? list/noh a
 0.5 / 1:  1.000  2.000
 1.5 / 2:  2.000  3.000
```

Then do a 2-d average, three different ways.  For this variable on a rectangular grid with no missing values, averaging is a linear operation, so order shouldn't matter and all three should give the same answer to within machine precision.

```
yes? let b = a[x=@ave]; let c = a[y=@ave]                                       
yes? list/noh a[x=@ave,y=@ave], b[y=@ave], c[x=@ave]
I / *:     2.000  2.000  2.000
```

Good.  But now constrain the region to omit half the rightmost cell: 

```
yes? list/noh/x=0:1.5 a[x=@ave,y=@ave], b[y=@ave], c[x=@ave]
I / *:     2.000  1.833  1.833
```

The right answer is (1 + .5*2 + 2 + .5*3)/(1+.5+1+.5) = (1+1+2+1.5)/3 = 5.5/3 = 1.833.  So the first result, from the simultaneous 2d average, is wrong -- it's not properly applying the partial-edge weights for the rightmost cell.

**Comment by AnsleyManke** [comment]
This was indeed in the memory management and improvements allowing larger regions for transformations by doing the calculation in chunks.  As part of that, the grid-box-sizes are collected, then the code says "trim if partial box at low end ... high end". But then it goes and gets the wrong information for the grid box edges to compare with the requested region ends.

So this is an easy fix.  Surprisingly we didn't have a test for multi-dimensioned transformations with endpoints other than at grid box edges. I've added these sorts of tests.

The same code starts off the computation for multi-dimensional averages, definite integrals, and standard deviations, so the bug and the fix apply to all of these.

We'll get you a test executable in the next couple of days and get this out to the public with an announcement about the bug.
