### ISSUE TITLE
_FillValue = nan, with no missing_value, data saved w/o _FillValue or missing_value

### ISSUE THREAD

**Issue by AnsleyManke** [NOAA-PMEL/Ferret#1883]
This comes up in 2018 Saildrone data. The attributes include only a _FillValue, not a missing_value 
and it's NaN

```
/home/users/ansley/projects/saildrone/ferretScripts> ncdump -h /home/data/saildrone/saildrone_arctic_2018/daily_files/1020/saildrone-gen_5-arctic_2018-sd1020-20180701T000000-20180701T055959-1_minutes-v2.1531526478435.nc | grep longitude
        double longitude(trajectory, obs) ;
                longitude:_FillValue = NaN ;
                longitude:coordinate = "latitude longitude timestamp" ;
                longitude:standard_name = "longitude" ;
                longitude:units = "degrees_east" ;
...
```
When this variable is written to a new file, it has neither a missing_value nor a _FillValue attribute

```
yes? save/file=a.nc/clobber longitude
 LISTing to file a.nc
yes? use a.nc
yes? show att longitude
     attributes for dataset: ./a.nc
 LONGITUDE.units = degrees_east 
 LONGITUDE.axis = X 
 LONGITUDE.long_name = LONGITUDE 
 LONGITUDE.history = From /home/data/saildrone/saildrone_arctic_2018/daily_files/1020/saildrone-gen_5-arctic_2018-sd1020-20180701T000000-20180701T055959-1_minutes-v2.1531526478435.nc 
```

**Comment by AnsleyManke** [comment]
This comes from the rather convoluted handling of these two attributes in Ferret. Internally we match only one bad-value flag. If there are both _FillValue and missing_value attributes then when the data is read, any values that match the _FillValue are replace with the missing_value and that is what's stored as the bad-value for skipping data in computations. On output, the missing_value is written, but containing the actual values in the data -- if ithad been different then it now contain the value of missing_value in the input file.  In the case where _FillValue was different on intput from missing_value, it will not be written unless the user specifically forces it to be output.  The missing_value attribute will in general be written instead.

If a file contains NaN as a _FillValue or missing_value attributes, ferret allows this but substitutes its default missing-value -1.e34. On output the -1.e34 will be written as the missing_value attribute. (Ferret isn't set up to write out NaN's.)

So here we have a case that finds a hole in all this logic.  The file has only a _FillValue attribute. When Ferret opens the file it notes this, and when data is read, it fills in any NaN's with -1.e34 and marks the bad-data flag as -1.e34.  It'll then work with the data correctly.  When it writes the data however, it sees that the _FillValue attribute from the original file is not the same as the bad-value flag and so does not write the _FillValue attribute.  It also hasn't written a missing_value attribute because there was not one in the original file.

The fix in cdf_list.F, is to add a test, if _FillValue from the file of origin differs from the bad-flag AND it's not  NaN, then do not write it. If the _FillValue was NaN, then write -1.e34.   In any other case where _FillValue will be different from the value in the original file and where it's not the same as the bad-flag, it's different from the bad-flab because there was a missing_value flag and we will have written a missing_value attribute.

**Comment by AnsleyManke** [comment]
This is fixed and a test for it added to the benchmarks.

**Comment by karlmsmith** [comment]
In GitHub as of 5960f853bd4d0fbed1a349c7c94bca3e5793f6ce
