### ISSUE TITLE
PLOT/VS produces no line, for certain viewport dimensions

### ISSUE THREAD

**Issue by AndrewWittenberg** [NOAA-PMEL/Ferret#1884]
This is a sensitive one -- it disappears if we slightly change any of the numbers below.  Might be another precision issue in the graphics.

Plot a diagonal line, in a particular viewport, in a window of a certain aspect ratio:

```
 	NOAA/PMEL TMAP
 	FERRET v7.42 (optimized)
 	Linux 2.6.32-754.el6.x86_64 64-bit - 07/10/18
 	19-Jul-18 20:12     

yes? set win/asp=.77 1
yes? def view/x=0.1:0.33330/y=0.55:0.9 v1; set view v1; go magnify
yes? plot/nolab/hl=-70:70/vl=-70:70/vs/line 1e6*{-1,1}, 1e6*{-1,1}
```
Looks good.  But now change the viewport x-dimension just slightly, and then run exactly the same PLOT command:

```
yes? def view/x=0.1:0.33331/y=0.1:0.45 v2; set view v2; go magnify
yes? plot/nolab/hl=-70:70/vl=-70:70/vs/line 1e6*{-1,1}, 1e6*{-1,1}
```

The line doesn't plot at all, in the second panel!

The bug disappears if we change the window aspect ratio, viewport definition, plotted points, the HLIMITS or VLIMITS, or eliminate "go magnify".  Is something going on with this particular combination of numbers, that is tickling a particular graphics bug?

This doesn't appear to be new; it shows up even in v6.8.2, dated 8/3/2012.

Here is the resulting plot:

![plot](https://user-images.githubusercontent.com/34082818/42976515-eb47c2aa-8b8f-11e8-98ec-fa1d9138548a.gif)

**Comment by AnsleyManke** [comment]
And, it happens both in Ferret and PyFerret.  I think your guess of precision issues of some sort is the place to start looking for this.

**Comment by AnsleyManke** [comment]
oops, didn't mean to close that.

**Comment by AnsleyManke** [comment]
The place to look is the pplus routine xyzplt, which is deciding, when we're drawing from one point to another, whether either of them lies outside the axis boundaries, and if so whether and where the line intersects a boundary.

**Comment by AnsleyManke** [comment]
This is fixed.  The pplus code has logic to tell whether the intercept between points crosses the plot boundary.  That test is now more robust.

Fixed in xyzplt.F

**Comment by karlmsmith** [comment]
I suspect, but am not sure, that the fix for this can result in some stray lines off the top left corner of the plot.  Most notable is time_plot_precision_hovmuller.gif with a green line going up to the top of the page.  The top left corner plot in bnplot_1.gif shows what maybe is an additional tic mark for the horizontal axis.  (It could actually be a tic mark now showing up and so not a problem.)

**Comment by AnsleyManke** [comment]
The previous fix had used a computed tolerance based on the size of the numbers being used.  A better fix is to do all of the computations and comparisons for whether and where the line crosses the boundary of the plot box using double precision. This is done, xyzplt.F

**Comment by AndrewWittenberg** [comment]
It looks like there are still problems in the version compiled 8/20/18.  Did Ansley's latest fix make it into that version?

```
 	NOAA/PMEL TMAP
 	FERRET v7.42 (optimized)
 	Linux 2.6.32-696.30.1.el6.x86_64 64-bit - 08/20/18
 	23-Aug-18 14:46     

yes? can mode verify
yes? def sym com "hl=-1:1/vs/line/dash x[gx=-2:2:.1], 0-1.3*cos(2*x[gx=-2:2:.1])"
yes? can view; set view ul; plot/vl=-4:4/($com)
yes? set view ur; plot/vl=-2:2/($com)
yes? set view ll; plot/vl=-1:1/($com)
yes? set view lr; plot/vl=-.5:.5/($com)
```

Here's the correct result, from the version compiled 7/10/18:

![line_bug_v20180710](https://user-images.githubusercontent.com/34082818/44545894-3fec3880-a6e4-11e8-8324-8891d13c8cd9.gif)

And here's what we get in the version compiled 8/20/18 -- note all the stray lines:

![line_bug_v20180820](https://user-images.githubusercontent.com/34082818/44545902-47abdd00-a6e4-11e8-9d1b-766127836bc8.gif)

**Comment by AnsleyManke** [comment]
Yes, the last official release is correct, more-recent builds are not, for this example anyway.  It looks like the additional change in the comments of July 30 and 31 are the culprit.

**Comment by AnsleyManke** [comment]
This is fixed in xyzplt.F.  The precision fix was correct, but it hadn't been implemented quite right.
