### ISSUE TITLE
Ferret crash applying strides to longitude axis

### ISSUE THREAD

**Issue by AnsleyManke** [NOAA-PMEL/Ferret#1890]
Ajay at NODC ran into this in the LAS at NODC. The dataset, 

https://data.nodc.noaa.gov/thredds/dodsC/cortad/Version5/cortadv5_WindSpeed.nc.html

has a longitude axis 8640 points long that's irregularly spaced. It's specifically marked with the point-spacing = uneven attribute and the axes have bounds defining the grid cell edges.  In LAS when making plots from this data, we apply striding on the 8640x4320 grid.  On reading the grid and resolving the context, Ferret crashes.  A subset of the dataset is attached.

```
yes? use https://data.nodc.noaa.gov/thredds/dodsC/cortad/Version5/cortadv5_WindSpeed.nc
yes? set axis/stride=16 `wind_speed,return=xaxis`
yes? shade/y=-2:2/L=1 wind_speed
**ERROR Ferret crash; signal = 11
```

If we override the irregular spacing with SET AXIS/regular `wind_speed,return=xaxis`, the script works ok.  

(Ajay is using an older version of Ferret in his LAS. This bug seems to be related to the dynamic coordinate storage implemented in Ferret v7.3, and LAS does not require the latest Ferret.
)

[cortad_subset.nc.gz](https://github.com/NOAA-PMEL/Ferret/files/2275838/cortad_subset.nc.gz)

**Comment by AnsleyManke** [comment]
This is  a bit of an odd grid, probably unintentionally. The longitude grid cell edges it defines leave a gap at x=180. The first grid cell has its lower limit at -179.9792,  and the upper limit of the last cell is at 179.9792.  This means that the axis length computed from the lower limit of the start to the upper limit of the end is less than a full 360 degrees of longitude, leaving a gap of 0.0416 degrees.  That's the size of a grid cell.  There should be a coordinate point right at x=180 but there isn't.

Show axis tells us the axis length is shorter than 360.
```
yes? show axis `wind_speed,return=xaxis`
 !-> sh axis LON
 name       axis              # pts   start                end
 LON       LONGITUDE         8640mi   179.96W(-179.96)     179.96E(179.96)
   Axis span (to cell edges) = 359.9584 (modulo length = 360)
```

Ferret detects this as a "subspan modulo axis" where the axis length is shorter than the modulo-longitude length, and so when getting get the axis length it's a case of an irregularly-spaced subspan-modulo axis, with a stride.  There is a bug in the dynamic coordinate code imn TM_WW_AX_1_N getting the axis limits when such an axis is has been strided.

I've created a benchmark test and written to Ajay.

**Comment by karlmsmith** [comment]
The change modified the output for err700_modulo.jnl:
```
 define axis/t0=1-jan-0000/units=days/t tax2 = { 3, 55, 103, 153, 203, 253, 303, 353}
 sh axis tax2
  name       axis              # pts   start                end
- TAX2      TIME                 8mi   04-JAN 00:00         19-DEC 00:00
+ TAX2      TIME                 8 i   04-JAN-0000 00:00    19-DEC-0000 00:00
 T0 = 1-JAN-0000
-   Axis span (to cell edges) = 365.2425 (modulo length = axis span)
+   Axis span (to cell edges) = 401
```
I assume this change is incorrect so reopening this ticket.

**Comment by karlmsmith** [comment]
Further update has fixed the invalid side effect.  Interesting change in another test showed up, but I suspect this change is a correct change.  See https://github.com/NOAA-PMEL/Ferret/commit/09361c83aef4e7c8d51e5bbb706a0179826b4871

**Comment by karlmsmith** [comment]
Just looking at the code, since this is back to using linemem, should the hi index be llen instead of llen+1 ?

**Comment by AnsleyManke** [comment]
The other change was in fact due to the llen+1 which should be llen. The change to the test err611_context_after_error.jnl was due to that, so the output of that test is unchanged from previous versions.

All fixed, benchmarks are consistent.
