### ISSUE TITLE
wrong variable labels (names instead of titles) when more than one variable is plotted

### ISSUE THREAD

**Issue by ssgromov** [NOAA-PMEL/Ferret#1911]
Consider the following commands:

let/title="@SR variable A"/units="K" a = x[i=1:10]
let/title="@SR variable B"/units="Pa" b = 1-x[i=1:10]
se vi left; pl a,b
se vi ur; pl a
se vi lr; pl b

The plot of both, a and b, should show the titles of both variables, instead it shows variable names, but not titles. Plotted alone, titles show up correctly (see the figure below). 

![image](https://user-images.githubusercontent.com/10381613/49955707-ca5edf00-ff03-11e8-934f-14f00f28d7ae.png)

Somehow it appeared between versions 7.0 and 7.4.

![image](https://user-images.githubusercontent.com/10381613/49955633-92f03280-ff03-11e8-8bf4-d94a84a65c50.png)

**Comment by AnsleyManke** [comment]
What you're seeing is a consequence of the changes for #1503.  It looks like there is still some more to do to get things right.  There, we were thinking of user-defined variables where the labels were created internally to show the difference between their different contexts, and which didn't let the user control the title. 

Right now, you can get the behavior you want with PLOT/KEY=TITLE  but we should be able to get back to the right behavior using the title on the plot when it's been defined. 

In Ferret v7.0 and previous:
```
 use coads_climatology

set v upper
let/title=January sst1 = sst[l=1]
let/title=May sst5 = sst[l=5]
let/title=September sst9 = sst[l=9]

! This was labeled with "sst[L=1]" etc even though titles were defined.
plot/x=300/y=20:65  sst1, sst5, sst9

! But file variables were correctly labeled with names and units
set v lower
plot/x=300/y=20:65/l=1 sst, airt, speh

```

Variables that aren't defined from file variables, such as you show above, did use the titles if they are defined.  Or, variables defined from multiple underlying variables also used the titles from variable definitions, but now do not. This example is another that in version 7.0 uses the titles that are defined and does not starting in v7.1 except with plot/key=title.

```
use coads_climatology
use levitus_climatology

let diffsst = sst[d=1,l=1] - temp[d=2,z=0,gxy=sst[d=1]]
let difftemps = sst[d=1,l=1] - airt[d=1,l=1]

set v upper; plot /x=300/y=20:65 diffsst, difftemps

let/title="COASDS sst - LEVITUS temp"/units="Deg C" diffsst = sst[d=1,l=1] - temp[d=2,z=0,gxy=sst[d=1]]
let/title="COASDS sst - COASDS airt"/units="Deg C"  difftemps = sst[d=1,l=1] - airt[d=1,l=1]

set v lower; plot /x=300/y=20:65 diffsst, difftemps
```

It should be possible to have the title be used for any user-defined variable that has a /TITLE=. The question is distinguishing internally between the variable-definition, SST[L=1],  and the variable title which might just be what's in the file, or might be a user-defined title.

**Comment by ssgromov** [comment]
Dear Ansley,
I obviously could not follow up on the developments since 7.0, and saw something similar in other issues but could not get it right. With /key=title it is a perfect way for me now.
Best and thanks,
Sergey
