### ISSUE TITLE
after plotting, `var, RETURN=SHAPE` crashes Ferret

### ISSUE THREAD

**Issue by AndrewWittenberg** [NOAA-PMEL/Ferret#1922]
This is a new bug in v7.442 (3/27/19), which was not in v7.44 (12/10/18).  This bug is crashing the standard "polymark.jnl" script when attempting to overlay some polygons on a plot.

```
 	NOAA/PMEL TMAP
 	FERRET v7.442 (optimized)
 	Linux 2.6.32-696.30.1.el6.x86_64 64-bit - 03/27/19
 	31-Mar-19 13:18     

yes? use coads_climatology
yes? let v1 = tsequence(sst[x=140w,y=0])
yes? let vx = v1
yes? say `vx,return=shape`
T
yes? plot/vs vx+{1,1,-1,-1,1}, 0*vx+{1,2,2,1,1}
yes? say `vx,return=shape`
**ERROR Ferret crash; signal = 11
```

But note that if we insert

```
yes? `say `v1,return=shape`
```

just before the last line, then instead of a crash we get an error:

```
 **ERROR: unknown defining grid: (C011,V001)
```

**Comment by AnsleyManke** [comment]
This is still issue #1916...  I'm working on it!

**Comment by AnsleyManke** [comment]
This is fixed.  I've written a routine to handle grid-context information saved by the evaluations for grave-accent returns.
