### ISSUE TITLE
parsing bug in qualifiers

### ISSUE THREAD

**Issue by AndrewWittenberg** [NOAA-PMEL/Ferret#1927]
May be related to #660 or #228: I'm noticing new (since last year) parsing problems in some of our standard scripts:

```
 	NOAA/PMEL TMAP
 	FERRET v7.5 (optimized)
 	Linux 2.6.32-696.30.1.el6.x86_64 64-bit - 04/25/19
 	26-Apr-19 19:53     

yes? let obs_yr1 = 1880
yes? let obs_yr2 = 2014
yes? def ax/t=1-jan-1880:1-jan-2015:`1/12`/unit=years/edge/cal=noleap tax_hist
 !-> def ax/t=1-jan-1880:1-jan-2015:0.08333333333333333/unit=years/edge/cal=noleap tax_hist
yes? let/title="ERSST.v5 obs (`obs_yr1`-`obs_yr2`)"/unit="#C" ts_obs = sst
 **ERROR: command syntax: " ts_obs =
```

This is another one that's sensitive to the specific text, in ways that shouldn't matter -- e.g. simply rename "obs_yr1" as "yr1", or remove the DEFINE AXIS line, and there's no longer a problem.

The bug was not in v7.42 (7/10/18) but then appears for the first time in v7.4202 (8/9/18).

**Comment by AndrewWittenberg** [comment]
Actually this goes back even earlier -- v7.42 still chokes on the following:

```
 	NOAA/PMEL TMAP
 	FERRET v7.42 (optimized)
 	Linux 2.6.32-754.el6.x86_64 64-bit - 07/10/18
 	26-Apr-19 20:21     

yes? let obs_yr1 = 1880
yes? let obs_yr2 = 2014
yes? def ax/t=1-jan-0051:1-jan-0150:.08333/unit=years/edge/cal=noleap tax_future
yes? let/title="ERSST.v5 obs (`obs_yr1`-`obs_yr2`)"/unit="K" ts_obs = sst[d=1]
 **ERROR: command syntax: 2`)"/unit=
```

**Comment by AnsleyManke** [comment]
I've found a possibility, info from the command qualifiers in DEFINE AXIS hanging around and trying to be applied when evaluating  obs_yr1.  

Testing now, but also heading home. I have a feeling this isn't quite going to be it, but it's a start. Have a good weekend!

**Comment by AnsleyManke** [comment]
Yes, this seems to be #228.  Re-initializing the qualifier information at the start of command parsing fixes it.
