### ISSUE TITLE
PyFerret axis labels with new fonts and super/subscripts are not centered

### ISSUE THREAD

**Issue by AndrewWittenberg** [NOAA-PMEL/Ferret#1928]
PyFerret axis labels with new fonts and super/subscripts are not centered.

```
 	NOAA/PMEL TMAP
 	PyFerret v7.444 (optimized)
 	Linux 3.10.0-957.10.1.el7.x86_64 - 04/16/19
 	29-Apr-19 13:14     

yes? set text/font=arial
yes? plot/x=0:3/y=0:3/set/vs {0,1},{0,1}
yes? ppl labset .2 .2 .2 .2
yes? ppl xlab "K<sup>2</sup> / (here are the denominator units)"
yes? ppl plot
```
![plot](https://user-images.githubusercontent.com/34082818/56914088-30966980-6a81-11e9-947a-49066ed22994.png)

**Comment by AnsleyManke** [comment]
It looks like it's the superscript spec that's causing it to get the location wrong. 

This is also wrong;
`plot/x=0:3/y=0:3/vs/title= "K<sup>2</sup> / (here are the denominator units)" {0,1},{0,1}`

This draws the label in the right place.

```
yes? set text/font=arial
yes? plot/x=0:3/y=0:3/set/vs {0,1},{0,1}
yes? ppl labset .2 .2 .2 .2
yes? ppl xlab "K2 / (here are the denominator units)"
yes? ppl plot
```

**Comment by AnsleyManke** [comment]
This is fixed.  The code that gets the width of the label had a bug in accounting for the smaller text used in subscripts or superscripts, wildly under-counting the length of the label.

Added a new test in bn_setting_text.jnl

**Comment by athulya-mrfp** [comment]
Hii Do you know how to give degree celsius symbol in the ppl ylab?

**Comment by ACManke** [comment]
I found this described in the documentation for the PyFerret command "set
text"

https://ferret.pmel.noaa.gov/Ferret/documentation/users-guide/commands-reference/SET#pyferret_embedded_symbols

**Comment by athulya-mrfp** [comment]
Yes I found it. Looks like default font does not work. When I changed the
font it worked. Thanks a ton!!!
Kind Regards

Athulya R
