### ISSUE TITLE
Error (actually warning) should not be printed with delta-T of 8.333E-2

### ISSUE THREAD

**Issue by karlmsmith** [NOAA-PMEL/Ferret#1931]
```code
def ax/t=1-jan-0001:1-jan-0100:8.33333333E-2/edge/cal=standard/unit=year tax1
 **TMAP ERR: error in time line definition
             8 is not valid in this calendar
show axis tax1
 name       axis              # pts   start                end
 TAX1      TIME              1188 r   16-JAN-0001 05:14    16-DEC-0099 18:56
T0 = 01-JAN-0000
   Axis span (to cell edges) = 99
```

The message arises from checking if the third colon-separated value is an ISO time.  Because of the `-` it does not automatically get disqualified as a time value and thus tries to parse it.  The attempt to parse the date/time in the original format fails silently.  The attempt to parse the ISO time prints the error message.  On failure the value is then parsed as a number and the command succeeds, but because of the error message one thinks it has not succeeded.

FYI - The return value of call to the old routine checking if it could be a time value is ignored and that call should be removed.  The check for the ISO time should be more strict - requiring the four digit year at a minimum.  But also it would be good if the routine parsing the command line could pass on that this is the third of the colon-separated arguments, and as such (I think) one could completely skip checking if it is a time value and go right to the parsing as a normal number.  (Possibly for more that T and F axes as well?)

**Comment by AnsleyManke** [comment]
good ideas - I like checking that we've already got the three items lo:hi:delta.

**Comment by AnsleyManke** [comment]
The answer is to not try to apply fancy translation of a coordinate string such as a date or LON/LAT coordinate spec 45W, to the delta-value in LO:HI:DELTA  specs.  The delta is just a numeric value in the units of the coordinate axis, and a time string or lon/lat value is an error anyway.

As far ss the routines that look at time strings to see if they may be ISO times or VAX-formatted strings, there are places internally where these are called on a date string that has to do with a modulo time axis like 15-MAR with no year.  So I'm leaving those routines alone.

Removing TM_DATE which is no longer needed.
