### ISSUE TITLE
how to keep the default shade key as continuous in Pyferret?

### ISSUE THREAD

**Issue by srinivasvl81** [NOAA-PMEL/Ferret#1945]
FILL/PALETTE=rnb/KEY=CONTINUOUS/LEV=(0.00,0.084,0.001)(inf) TKE[Z=1:100@AVE]
ppl shakey 1, 1, 0.16, 0, 3, 9, 8.85, 9.14, 1.4, 6.95
ppl fill
GO land

After, "ppl fill", the colour bar again appears in bands. 
I had the same problem with palette which was changing back to the default one after ppl fill. So, I used the " ppl shaset spectrum= rnb " command to set the default palette.

Is there any method in Pyferret in which I can set the default shade, fill key=continuous ?

Thank you.

**Comment by AnsleyManke** [comment]
Hi,
Questions about how to use PyFerret/Ferret commands are answered in the Users' List forum.  Please subscribe by following the instructions here: 

https://ferret.pmel.noaa.gov/Ferret/email-users-group
