### ISSUE TITLE
SAVE/APPEND of a string variable limits the string length to the length first written

### ISSUE THREAD

**Issue by AnsleyManke** [NOAA-PMEL/Ferret#1946]
Billy discovered this, defining string variables on a time axis and writing successive timesteps to a file using /append.  The first write sets the string dimension to the maximum size used for that write, and any successive writes do not change that length, which causes longer strings to be truncated.

```
yes? let strings = {"abc", "defg", "hijkl", "lmnopq"}
yes? define axis/t=1:4:1 taxis
yes? let tt = t[gt=taxis]
yes? let tstrings = reshape(strings, tt)

yes? save/clobber/file=a.nc/l=1 tstrings
yes? save/append/file=a.nc/L=2:4 tstrings
yes? sp ncdump  a.nc
netcdf a {
dimensions:
        TAXIS = UNLIMITED ; // (4 currently)
        STRING1_3 = 3 ;
variables:
        double TAXIS(TAXIS) ;
                TAXIS:axis = "T" ;
        char TSTRINGS(TAXIS, STRING1_3) ;
                TSTRINGS:long_name = "RESHAPE(STRINGS, TT)" ;

// global attributes:
                :history = "FERRET V7.504 (optimized) 23-Jul-19" ;
                :Conventions = "CF-1.6" ;
data:

 TAXIS = 1, 2, 3, 4 ;

 TSTRINGS =
  "abc",
  "def",
  "hij",
  "lmn" ;
}
```

A workaround is to first somehow write the longest length to the first timestep, but is it possible to change the string dimension length of an existing file when we're appending? Or, give the user control of the string-length dimension when first writing the file, similar to the /ILIMITS /JLIMITS etc qualifiers.

for info, here's the workaround:
```

! First define things so the first string is long enough.

yes? let strings = {"xxxxx",  "defg", "hijkl", "lmnopq"}
yes? define axis/t=1:4:1 taxis
yes? let tt = t[gt=taxis]
yes? let tstrings = reshape(strings, tt)

! Save the first timestep, so string-dim is long enough.
yes? save/clobber/file=a.nc/l=1 tstrings
 
! Now define the variable we want
yes? let strings = {"abc", "defg", "hijkl", "lmnopq"}

! Use SAVE/APPEND/L=1 to overwrite the value in the file
yes? save/append/file=a.nc/l=1 tstrings

! and add on the rest of the steps.
yes? save/append/file=a.nc/L=2:4 tstrings

yes? sp ncdump a.nc
netcdf a {
dimensions:
        TAXIS = UNLIMITED ; // (4 currently)
        STRING1_5 = 5 ;
variables:
        double TAXIS(TAXIS) ;
                TAXIS:axis = "T" ;
        char TSTRINGS(TAXIS, STRING1_5) ;
                TSTRINGS:long_name = "RESHAPE(STRINGS, TT)" ;

// global attributes:
                :history = "FERRET V7.504 (optimized) 23-Jul-19" ;
                :Conventions = "CF-1.6" ;
data:

 TAXIS = 1, 2, 3, 4 ;

 TSTRINGS =
  "abc",
  "defg",
  "hijkl",
  "lmnop" ;
}

```

**Comment by AnsleyManke** [comment]
If we write out a subset of string variables from a file,  the string-length attribute from the input file is used.  So this is an issue only when defining string variables with pyferret commands.  There, the first write looks at the strings being written and defines the string length dimension as the maximum length in the strings being written.  Once that's set in the file it can't be changed in subsequent writes when appending more data.

To allow for control of this:
- When setting up a string-length attribute, make it longer by default.  Maybe 50 characters?  Or 100? We don't want to go overboard; the strings seem to be padded to the length given so making them larger increases the size of the file.
- If appending to a string variable and the strings now being written are longer than the string dimension, issue an error message.
- Allow the user to set the string length when first writing the variable.  We have qualifiers SAVE/ILIMITS /JLIMITS etc to define an X or Y axis on writing, larger than what that command is going to write, so maybe SAVE/SLIMITS  or SAVE/STRLEN

**Comment by AnsleyManke** [comment]
Since this is a fairly unusual case, I am ONLY implementing SAVE/STRLEN= as an option, and not arbitrarily extending the string length as suggested in bullet 1 just above.

So, if the user tries to append to a string variable and the new strings are too long, we get an error message, suggesting that the first WRITE creating the variable needs /STRLEN=

/STRLEN= can be given on the first write of a variable whether it's a user-variable or a file variable.

**Comment by karlmsmith** [comment]
Eventually Ferret should support the (relatively new) string nc variable type instead of making these character arrays of a fixed dimension.
