### ISSUE TITLE
Increase default memory size

### ISSUE THREAD

**Issue by karlmsmith** [NOAA-PMEL/Ferret#1958]
(From GFDL 2019 visit)
The default max memory allocation for Ferret/PyFerret should be greatly increased so that users normally will not need to reset the default.  Since this is a maximum (instead of an actual allocation), if they do have to reset the default, it should be to reduce this maximum.

The current default is "/size=25.6" which is about 200M.  Maybe make the default 2G?
Also need to update documentation.

**Comment by AndrewWittenberg** [comment]
I generally start up using `ferret -memsize 128`, i.e. 1G.  So I know that'd work smoothly on all the GFDL systems.

**Comment by AnsleyManke** [comment]
This is done; it's set it to 1G

**Comment by karlmsmith** [comment]
PyFerret sets default values in other locations (__init__.py and libpyferret.c - rather ugly, but consequence of supplying default argument values).  These defaults updated in commit https://github.com/NOAA-PMEL/PyFerret/commit/024bdea8ebb5b2989b715f4df7518a5e566a4831
