### ISSUE TITLE
Failures in call to ef_get_axis_dates

### ISSUE THREAD

**Issue by karlmsmith** [NOAA-PMEL/Ferret#1971]
A user trying to write their own external function found that the example external function dates.F crashed on the call to ef_get_axis_dates.

**Comment by karlmsmith** [comment]
The problem was the argument list to EF_GET_AXIS_DATES had change and the example external functions were not updated (adding the precision input argument and the string length output argument).  Once that was updated, everything was working fine for precision 3-7, but not for precision 1 and 2.

The function EF_GET_DATE_TSTEP (called by EF_GET_AXIS_DATES) calls SECS_TO_DATE_OUT which returns the correctly formatted date string.  However, EF_GET_DATE_TSTEP was then re-truncating the time string.  After removing this duplicate truncation, precision 1 and 2 are working correctly.

All of these changes were to support ISO time and fractional seconds.  The example functions were updated but since they are never actually used (now internal functions) other that dates.F, not able to test.  Also, most of these expect dates in the original format, not ISO format.  Comments were added to the functions that they would fail if dates are in ISO format.

**Comment by karlmsmith** [comment]
Fixed in https://github.com/NOAA-PMEL/Ferret/commit/b23e08d3e861f89c24be747dcae11757ec7d1257

**Comment by karlmsmith** [comment]
Modified dates.F to add a precision argument (as a string) to this external Ferret function.  Added a unit test with all the precision options.  The unit test only uses Ferret-format dates; probably should add ISO dates just to be sure they also work as expected.

**Comment by AnsleyManke** [comment]
I have updated this function on dunkel

I will add this function to the documentation.  A quick few tests shows the function is working correctly for ISO dates.

**Comment by AnsleyManke** [comment]
This is documented.  I also changed the function description and argument description in the function itself to make them clearer.
