### ISSUE TITLE
inconsistent unweighted transformations (@sum, @ngd, @nbd) along modulo axis

### ISSUE THREAD

**Issue by AndrewWittenberg** [NOAA-PMEL/Ferret#1981]
This issue was discovered by Chris Milly at GFDL.  An unweighted sum (`@sum`) over different modulo intervals (e.g. x=300:360 and x=-60:0 on a longitude axis), gives different results, if the edges of the summing region are aligned with the cell bounds.
```
 	NOAA/PMEL TMAP
 	FERRET v7.52 (optimized)
 	Linux 2.6.32-754.23.1.el6.x86_64 64-bit - 12/03/19
 	18-Jun-20 15:09     

yes? def ax/edge/x=0:360:1.25/unit=degrees_east/modulo xax
yes? let v = 1+0*x[gx=xax]
yes? list/nohead v[x=300:360@sum], v[x=-60:0@sum]
I / *:     48.00  49.00
```
In the latter case, an extra (and undesired) point is included in the sum:
```
yes? list/nohead v[x=300:360@ngd], v[x=-60:0@ngd]
I / *:     48.00  49.00

yes? list/nohead/x=300:360 v, xboxlo[gx=v]
59.4W / 241:  1.000  300.0
58.1W / 242:  1.000  301.3
...
1.9W  / 287:  1.000  357.5
0.6W  / 288:  1.000  358.8

yes? list/nohead/x=-60:0 v, xboxlo[gx=v]
59.4W  / -47:  1.000 -60.00
58.1W  / -46:  1.000 -58.75
...
1.9W   /  -1:  1.000  -2.50
0.6W   /   0:  1.000  -1.25
0.6E   /   1:  1.000   0.00
```

So what to do?

(1) It's clear that the resulting sum really ought to be identical in these two cases; so Ferret ought to do a fuzzy comparison of the edges, based on its internal precision.

(2) This highlights something that, at the very least, should be more clearly documented in the user guide: as currently implemented, an unweighted sum includes any valid cells whose _bounds_ (not just the cell's central point) overlap (and possibly just abut or touch) the summing region.

This makes intuitive sense for the weighted average and integral, since the weight of the overlapping region diminishes as the overlap shrinks.  But for the unweighted `@sum`, `@ngd`, etc., I had always thought that they only included valid cells whose _centers_ (central coordinate values) fell within the summing region.  This was based on the [documentation](https://ferret.pmel.noaa.gov/Ferret/documentation/users-guide/variables-xpressions/XPRESSIONS#_VPINDEXENTRY_503), which says:

_"If the region is specified in world coordinates, the edge points are not weighted—they are wholly included in or excluded from the calculation, depending on the location of the **grid points** with respect to the specified limits."_

However, that appears to be incorrect.  As currently implemented, it's not the _grid points_ that are compared, but rather the _cell bounds_.  Perhaps Ferret does it that way to simplify the implementation of the weighted sums and integrals; if so, then this needs to be documented properly [here](https://ferret.pmel.noaa.gov/Ferret/documentation/users-guide/variables-xpressions/XPRESSIONS#_VPINDEXENTRY_503) and [here](https://ferret.pmel.noaa.gov/Ferret/documentation/users-guide/variables-xpressions/XPRESSIONS#GeneralInfo), supported by pictures and examples, since it is unintuitive.  Alternatively, the implementation of unweighted sums could be changed to match the current documentation, which I do feel would be much more intuitive and less problematic for users.

(3) With the present implementation, a user workaround is to ensure that with unweighted transformations (like `@sum`, `@ngd`, `@nbd`), their desired summing region should only touch (i.e. fall within or on the bounds of) cells whose values they actually want included in the sum.  This should also be described clearly in the documentation.  So to be safe in the above example, we'd need to do the sum with something like this:
```
yes? let eps = 0.001
yes? list/nohead v[x=`300+eps`:`360-eps`@sum], v[x=`-60+eps`:`0-eps`@sum]
I / *:     48.00  48.00
```

**Comment by AnsleyManke** [comment]
I agree - unweighted means that partial grid boxes aren't used for weighting, but this shows they are taken into account.  We'd still have to think whether there's even still a need for some fuzzy arithmetic for grids which for instance are fractions of degrees, say 1/3 degree in lon or lat, where the coordinate values aren't necessarily going to match the specification given on the command line.

**Comment by AnsleyManke** [comment]
This is not any issue with the @SUM and other transformations, but with the data that's being loaded.  The sequence is

- What's the index range that corresponds to the given world-coordinate range?  Go load that (doing anything else that's needed to evaluate the expression).
- Now what's the transformation?  Apply it to the data that's loaded.

Too much data is being sent when the specification is x=-60:0, ending right at the end of the axis.  In effect when the upper coordinate of the given range matches the upper grid-cell edge, it should be applying a modulo operation but isn't.

``
yes? def ax/edge/x=0:360:1.25/unit=degrees_east/modulo xax
yes? let v = 1+0*x[gx=xax]

yes? list/x=358:360 v
             VARIABLE : 1+0*X[GX=XAX]
             SUBSET   : 2 points (LONGITUDE)
 1.9W / 287:  1.000
 0.6W / 288:  1.000

yes?  list/x=-2:0 v
             VARIABLE : 1+0*X[GX=XAX]
             SUBSET   : 3 points (LONGITUDE)
 1.9W  / -1:  1.000
 0.6W  /  0:  1.000
 0.6E  /  1:  1.000

but, 

yes?  list/x=-362:-360 v
             VARIABLE : 1+0*X[GX=XAX]
             SUBSET   : 2 points (LONGITUDE)
 1.9W    / -289:  1.000
 0.6W    / -288:  1.000

``

When loading a range of data along an axis, the index range is computed.  The routine doing this makes several specific checks including does the world-coordinate match the upper-edge of the topmost grid cell of the axis, but didn't distinguish this case, where it needs to decide whether to handle 0 as the lower edge of the first grid cell or the modulo-ed upper edge of the last cell.  

Now it will distinguish whether we've asked for a range that should be handled as a modulo-axis request ending at the top edge of the axis, versus a single point. I do think that if we ask for just "list/x=-2:0 v" then we expect to get the first grid point, in the grid cell x=[0,1.25].  

```

yes? def ax/edge/x=0:360:1.25/unit=degrees_east/modulo xax
yes? let v = 1+0*x[gx=xax]
yes? list/nohead v[x=300:360@sum], v[x=-60:0@sum]
I / *:     48.00  48.00

yes? list/x=358:360 v
             VARIABLE : 1+0*X[GX=XAX]
             SUBSET   : 2 points (LONGITUDE)
 1.9W / 287:  1.000
 0.6W / 288:  1.000

yes? list/x=-2:0 v
             VARIABLE : 1+0*X[GX=XAX]
             SUBSET   : 2 points (LONGITUDE)
 1.9W  / -1:  1.000
 0.6W  /  0:  1.000

```
