### ISSUE TITLE
parser decodes qualifiers before grave expressions

### ISSUE THREAD

**Issue by karlmsmith** [NOAA-PMEL/Ferret#228]
**Reported by steven.c.hankin on 18 Oct 2002 21:42 UTC**
The reason for this order is so that qualifiers can be used in the context of
grave expressions.  The solutions requires considerable added complexity to the
parser.

yes? let region = "x=0:360"
yes? say `region`
 !-> MESSAGE/CONTINUE x=0:360
x=0:360
yes? set region/`region`
 **ERROR: unknown command qualifier: `region`

Migrated-From: http://dunkel.pmel.noaa.gov/trac/ferret/ticket/467

**Comment by karlmsmith** [comment]
**Comment by Ansley.B.Manke@noaa.gov on 6 Nov 2003 18:03 UTC**
Reassign to Ansley

**Comment by AnsleyManke** [comment]
See issue 1927: initialize command-qualifier flag storage at the start of the parsing routine.
