### ISSUE TITLE
look into annotations on plot keys

### ISSUE THREAD

**Issue by karlmsmith** [NOAA-PMEL/Ferret#254]
**Reported by @AnsleyManke on 15 Jan 2003 20:25 UTC**
(Helge Avlesen, Dec 11,2002)

It'd be nice to use variable titles, if available, in the 
key at the bottom of plots with multiple plot lines or
overlays.  As is, we get a long ugly string in the label.  

use coads_climatology
use levitus_climatology

let/title="Jan sst" sst1 = sst[D=1,L=1]
let/title="Mar sst" sst3 = sst[D=2,L=3]
let/title="Sep sst" sst9 = sst[D=3,L=9]

plot/y=0 sst1, sst3, sst9

Migrated-From: http://dunkel.pmel.noaa.gov/trac/ferret/ticket/498

**Comment by karlmsmith** [comment]
**Comment by Jonathan.S.Callahan@noaa.gov on 21 Oct 2003 20:16 UTC**
Moving from the hankin@pmel.noaa.gov user to the Steven.C.Hankin@noaa.gov user.

**Comment by karlmsmith** [comment]
**Comment by Ansley.B.Manke@noaa.gov on 6 Nov 2003 18:58 UTC**
Move to Ferret Tasksreassigning to Ansley, lower the priority

**Comment by karlmsmith** [comment]
**Comment by Ansley.B.Manke@noaa.gov on 10 Nov 2003 21:56 UTC**
using titles automatically wouldn't in general
distinguish lines.

How about if a line style (bug 297) includes a
custom key string

**Comment by karlmsmith** [comment]
**Comment by Ansley.B.Manke@noaa.gov on 5 Nov 2004 19:19 UTC**
Changing Component of bugs in "Ferret Tasks" from All to Main

**Comment by karlmsmith** [comment]
**Modified by ansley.b.manke on 4 Jan 2011 19:29 UTC**

**Comment by AnsleyManke** [comment]
The qualifier /KEY=TITLE has resolved this:

```
yes? use coads_climatology
yes? let/title="Jan sst" sst1 = sst[D=1,L=1]
yes? let/title="Mar sst" sst3 = sst[d=1,l=3]
yes?  let/title="Sep sst" sst9 = sst[D=1,L=9]

yes? plot/key=title/y=0 sst1, sst3, sst9

```
![legend](https://user-images.githubusercontent.com/5122690/78934859-8381ea80-7a60-11ea-8c96-681106bf476f.png)


The titles used are "Jan sst" etc.
