### ISSUE TITLE
Bomb on EPIC files with time and time2 in data types other than long

### ISSUE THREAD

**Issue by karlmsmith** [NOAA-PMEL/Ferret#33]
**Reported by steven.c.hankin on 17 Jul 2000 22:11 UTC**
Ferret croaks on modified EPIC files that encode the variables time and time2
in data types other than long.

The attached July 17 message details the problem.

---------------

Hi Kev,

We are increasingly encountering DODS EPIC data sets that do not conform to the
EPIC standards used at PMEL. e.g.
http://pogo.whoi.edu/cgi-bin/nph-nc/data/ArabianSea/models/ecmwf/ecmwf_buoy_obs_
monthly.epic
(see below)

The reason that Ferret craps on these time axes is that the netCDF variables
time and time2 are encoded as float instead
of long, as expected.

To resolve the problem we need to correct the routines cd-rd_er_1.F and
cd_rd_ep_arr.F. The routines need to use the
netCDF V3 features that automatically convert data types (instead of using
NCVGT1 and NCVGT) -- analagous to the
changes that you made to cd_read.F, but simpler.

This is not a high priority change ... but it is something to fit into our
discussions over the next couple of days.

    - steve

---------

/export/home/ja3/hankin/tmp> ferret
        NOAA/PMEL TMAP
        Program FERRET
        Version 5.21 - 06/15/00
        17-Jul-00 14:52

yes? use
"http://pogo.whoi.edu/cgi-bin/nph-nc/data/ArabianSea/models/ecmwf/ecmwf_buoy_obs
_monthly.epic"

yes? show data
     currently SET data sets:
    1>
http://pogo.whoi.edu/cgi-bin/nph-nc/data/ArabianSea/models/ecmwf/ecmwf_buoy_obs_
monthly.epic
(default)
 name     title                             I         J         K         L
 BP       mean sea level pressure          1:1       1:1       1:1       1:28
 SST      sea surface temperature          1:1       1:1       1:1       1:28
 TEMP     air temperature at 2m            1:1       1:1       1:1       1:28
 WNDE     east wind                        1:1       1:1       1:1       1:28
 WNDN     north wind                       1:1       1:1       1:1       1:28
 RH       relative humidity                1:1       1:1       1:1       1:28
 SPECHUM  specific humidity                1:1       1:1       1:1       1:28
 WNDS     wind speed                       1:1       1:1       1:1       1:28

yes? show grid/l sst
    GRID GEB1
 name       axis              # pts   start                end
 LON       LONGITUDE            1 r   61.875W              61.875W
 LAT       LATITUDE             1 r   15.14N               15.14N
 DEPTH     DEPTH (m)            1 r-  0                    0
STOP: SECS_TO_DATE

Migrated-From: http://dunkel.pmel.noaa.gov/trac/ferret/ticket/94

**Comment by karlmsmith** [comment]
**Comment by Jonathan.S.Callahan@noaa.gov on 21 Oct 2003 20:16 UTC**
Moving from the hankin@pmel.noaa.gov user to the Steven.C.Hankin@noaa.gov user.

**Comment by karlmsmith** [comment]
**Comment by Ansley.B.Manke@noaa.gov on 3 Nov 2003 23:13 UTC**
reassign to Ansley

**Comment by AnsleyManke** [comment]
closing this.  We don't have the files, but for sure Ferret/PyFerret now uses modern netCDF calls.
