### ISSUE TITLE
curvilinear grid (non-monotonic lon., outside [0,360]) shade plot produces strange cells

### ISSUE THREAD

**Issue by karlmsmith** [NOAA-PMEL/Ferret#531]
**Reported by Remik Ziemlinski on 7 Feb 2005 23:58 UTC**
Curvilinear grid not monotonic in longitude and outside the [degree range
doesn't plot correctly with SHADE.  A script courtesy of Andrew Whittenberg:

!-----------------------------------------------
use "in.nc"
set reg/y=60n:90n

! The following works fine
shade/i=1:350 kmt,geolon_t,geolat_t; go land

! But the following gives a screwy plot.  Could it be that the
! upper edges of the high-end cells are wrapping around to the
! left side of the plot?
!SET VIEWPORT UL
shade/i=1:351 kmt,geolon_t,geolat_t; go land

! Plotting all of the cells gives really weird results,
! including overplotting some of the data at 180E.
!SET VIEWPORT UR
shade kmt,geolon_t,geolat_t; go land

! Now define a new longitude variable that is strictly monotonic
! along each latitude row.  Note that this new variable now spans a
! wider range than the original [0,360) interval. 
let branch = IF geolon_t[i=@ddb](0,360]) GE 0 OR i[EQ 1 THEN 0 ELSE 1
let shift = 360*branch[i=@rsum](gi=geolon_t])
let/title="`geolon_t,r=title`"/unit="`geolon_t,r=unit`" \\
   lon_mono = geolon_t + shift

! Plot the data using this new longitude coordinate
!SET VIEWPORT LL
shade kmt,lon_mono,geolat_t; go land

! So Ferret will plot the data correctly as long as the longitudes are
! monotonic.  But this last plot isn't very attractive -- there ought to be
! some way to tell Ferret to wrap that data that extends past 360E around to
! the other side of the plot.  Here's a two-step hack:
!SET VIEWPORT LR
shade/hl=0:360 kmt,lon_mono,geolat_t
shade/lev/ov kmt,lon_mono-360,geolat_t
go land

! Unfortunately, this does leave a small gap on the left side of the
! plot -- I'm not sure why!

Migrated-From: http://dunkel.pmel.noaa.gov/trac/ferret/ticket/1166

**Comment by karlmsmith** [comment]
**Comment by Remik.Ziemlinski@noaa.gov on 8 Feb 2005 00:05 UTC**
Sample dataset for script in bug description:

ftp://ftp.gfdl.noaa.gov/pub/rsz/in.nc

**Comment by karlmsmith** [comment]
**Comment by Ansley.B.Manke@noaa.gov on 19 May 2005 20:56 UTC**
New qualifier SHADE/MOD and CONTOUR/MOD lets us use /HLIMITS to get the desired
region.  This kind of thing

   shade/hl=0:360 kmt,lon_mono,geolat_t
   shade/lev/ov kmt,lon_mono-360,geolat_t

can be accomplished with

   shade/hlim=0:360/MOD kmt, geolon_t, geolat_t

There are still going to be gaps because the SHADE command does not have a way
to go to the cell edges...

**Comment by karlmsmith** [comment]
**Comment by ansley.b.manke on 4 Nov 2008 19:49 UTC**
Adding Andrew to the CC list where he is mentioned in the ticket comments.

**Comment by karlmsmith** [comment]
**Attachment from Remik.Ziemlinski@noaa.gov on 8 Feb 2005 00:00 UTC**
monotonic lon., [0,360] curvilinear grid shade plot example (it works)
REPLACE THIS TEXT WITH UPLOADED FILE ./attachments/TRAC_1166_GIT_531/gridspec_problem.gif

**Comment by karlmsmith** [comment]
**Attachment from Remik.Ziemlinski@noaa.gov on 8 Feb 2005 00:02 UTC**
non-monotonic lon. grid outside [0,360] shade plot example (incorrect)
REPLACE THIS TEXT WITH UPLOADED FILE ./attachments/TRAC_1166_GIT_531/in.nc.gif

**Comment by ddb** [comment]
Ummmm, what?
