### ISSUE TITLE
parsing bug: immediate mode qualifiers

### ISSUE THREAD

**Issue by karlmsmith** [NOAA-PMEL/Ferret#660]
**Reported by @AndrewWittenberg on 27 Jan 2006 18:08 UTC**
Originally reported via email on 5 Apr 2004.

```
        NOAA/PMEL TMAP
        FERRET v5.81  
        Linux(g77) 2.4.18 - 07/14/05
        27-Jan-06 13:00     

yes? let a = 1
yes? def ax/t=1:10:1 tax_`a`
 **ERROR: invalid command: delta values may only modify variable names
```
Here is a workaround:
```
yes? def sym a `a`
 !-> def sym a 1
yes? def ax/t=1:10:1 tax_($a)
 !-> def ax/t=1:10:1 tax_1
```
Migrated-From: http://dunkel.pmel.noaa.gov/trac/ferret/ticket/1381

**Comment by karlmsmith** [comment]
**Comment by Andrew.Wittenberg@noaa.gov on 27 Jan 2006 18:32 UTC**
A possibly related problem for SET REGION, with a similar workaround.
This one was reported via email on 18 Oct 2002.

        NOAA/PMEL TMAP
        FERRET v5.81  
        Linux(g77) 2.4.18 - 07/14/05
        27-Jan-06 13:26     

yes? let region = "x=0:360"
yes? say `region`
 !-> MESSAGE/CONTINUE x=0:360
x=0:360
yes? set region/`region`
 **ERROR: unknown command qualifier: `region`

Workaround:

yes? def sym region_sym `region`
 !-> def sym region_sym x=0:360
yes? set region/($region_sym)
 !-> set region/x=0:360

**Comment by karlmsmith** [comment]
**Comment by Ansley.B.Manke@noaa.gov on 27 Jan 2006 22:08 UTC**
Further comments, no solutions yet.

These are both command-parsing difficulties.

In the first example,   

   yes? let a = 1
   yes? def ax/t=1:10:1 tax_`a`
    **ERROR: invalid command: delta values may only modify variable names

When going to get what `a` is, Ferret gets the "context" of the command as
t=1:10:1, saving the min and max and delta as t=1, 10, and 1. The error says,
`a` cannot have a delta.  Here is a clue, not a solution, but note that this
sequence works fine:

   yes? let a = XSEQUENCE({1})
   yes? def ax/t=1:10:1 tax_`a`
    !-> def ax/t=1:10:1 tax_1

(when we've just used "let a=1", why does Ferret try to apply /t=1:10:1 to the
variable a?)


--- 
in fiddling with the second example, it works as desired if we try a space
between SET REGION and the region string:

   yes? let xreg = "/x=0:180"
   yes? set region `xreg`
   yes? show region
   default region:
           X=0:180
           Y/J is unspecified
           Z/K is unspecified
           T/L is unspecified

   yes? cancel region
   yes? let yreg = "/y=12"
   yes? set region `xreg``yreg`
    !-> set region /x=0:180/y=12
   yes? show region
   default region:
           X=0:180
           Y=12
           Z/K is unspecified
           T/L is unspecified

The problem with SET REGION`region` is that in the command parsing,
parse_command.F before even hitting repl_exprns.F, the string REGION`region` is
deemed to be not a valid string.  Can we do the test on only the part of the
string before the grave accents?

**Comment by karlmsmith** [comment]
**Modified by ansley.b.manke on 5 Jan 2011 19:59 UTC**

**Comment by karlmsmith** [comment]
**Comment by andrew.wittenberg on 2 May 2011 21:29 UTC**
Adding the formatting back into the example:

```
        NOAA/PMEL TMAP
        FERRET v6.7 (nc413snapshot)
        Linux rh5 (gfortran) 2.6.18-238.1.1.el5P - 04/28/11
         2-May-11 17:29     

yes? let a = 1
yes? def ax/t=1:10:1 tax_`a`
 **ERROR: invalid command: delta values may only modify variable names
yes? def sym a `a`
 !-> def sym a 1
yes? def ax/t=1:10:1 tax_($a)
 !-> def ax/t=1:10:1 tax_1
```

**Comment by AndrewWittenberg** [comment]
As of Ferret v7.4.4.4, the first example appears to be fixed:

```
 	NOAA/PMEL TMAP
 	PyFerret v7.444 (optimized)
 	Linux 3.10.0-957.10.1.el7.x86_64 - 04/16/19
 	17-Apr-19 13:37     

yes? let a = 1
yes? def ax/t=1:10:1 tax_`a`
yes? sho ax tax_1
 name       axis              # pts   start                end
 TAX_1     T                   10 r   1                    10
   Axis span (to cell edges) = 10
```
But the second one isn't:
```
yes? let region = "x=0:360"
yes? say `region`
x=0:360
yes? set region/`region`
 **ERROR: unknown command qualifier: `region`

```

**Comment by AnsleyManke** [comment]
This is a long-standing bug in the parser.  When the grave-accent expression is right after a slash, it isn't evaluated.  Unlike symbol substitution which is done right near the start of parsing, grave-accent evaluation is done as the command's parts are identified and checked for correctness: command, qualifiers, sub-commands, arguments.

I can go and look at the point where it's testing qualifiers for valid strings, if there's a grave-accent, have it handle this.

```
yes? let region = "x=0:360"
yes? say `region`
yes? set region/`region`
 !-> set region/x=0:360
 
! multiple substitutions in the command:
yes? let xregion = "x=0:360"
yes? let yregion = "y=15:45"
yes? set region/`xregion`/`yregion`
 !-> set region/x=0:360/y=15:45

yes? let style="color=blue"
yes? plot/`style`/i=1:15 1./i
 !-> plot/color=blue/i=1:15 1./i

```
