### ISSUE TITLE
say `var[d=fname.cdf],return=size`  fails

### ISSUE THREAD

**Issue by karlmsmith** [NOAA-PMEL/Ferret#722]
**Reported by Ansley B Manke on 3 Oct 2006 21:24 UTC**
yes? use levitus_climatology.cdf
yes? say `temp[**ERROR: invalid command:  use RETURN= shape,size,grid,title,bad,t0,units,dset,
            dsetnum,dsetpath,dsettitle,*size,*start,*end,
            *units,*axis,nc_scale,nc_offset,user_scale,user_offset,
            calendar,dtype
          temp[d=levitus_climatology.cdf](d=levitus_climatology.cdf],return=size`
),return=size

Note it works fine if we don't specify the dataset, or even if we use a dataset
number or name without the .cdf extension.

yes? say `temp[d=levitus_climatology],return=size`
 !-> MESSAGE/CONTINUE 1296000
1296000

This is a parsing error in repl_exprns.F where the code is looking for a piece
in the command string of the form  varname.attname

Migrated-From: http://dunkel.pmel.noaa.gov/trac/ferret/ticket/1447

**Comment by karlmsmith** [comment]
**Comment by Ansley.B.Manke@noaa.gov on 5 Oct 2006 16:41 UTC**
fixed in repl_exprns.F, added new benchmark test err600_returnsize.jnl to test it.

**Comment by AnsleyManke** [comment]
Or maybe it's in some of the other changes to RETURN=  

This behaves like something isn't being initialized.
