### ISSUE TITLE
symbol substitution inside a "REPEAT loop assigned to a symbol" 

### ISSUE THREAD

**Issue by karlmsmith** [NOAA-PMEL/Ferret#756]
**Reported by @AndrewWittenberg on 29 Dec 2006 20:45 UTC**
May be related to bug 1303 or bug 558.  In the first loop, symbol translation
proceeds just fine, updating the symbol each time through the loop.

Next, we assign the loop to a symbol, and then execute that loop-symbol.  But
now, while the symbols "A" inside the loop are apparently still being updated
(as seen with SHOW SYMBOL), they're not translated properly in the output.  Is
this a parsing or stack-level bug?

        NOAA/PMEL TMAP
        FERRET v6.01  
        Linux(g77) 2.6.9-42. - 12/13/06
        29-Dec-06 15:24     

yes? can mode verify
yes? rep/j=1:3 (def sym a `j`; show sym a; say ($a))
A = "1"
1
A = "2"
2
A = "3"
3
yes? def sym a old
yes? def sym loop rep/j=1:3 (def sym a \\`j\\`\\; show sym a\\; say (\\$a))
yes? show sym loop
LOOP = "rep/j=1:3 (def sym a `j`; show sym a; say ($a))"
yes? ($loop)
A = "1"
old
A = "2"
old
A = "3"
old

Migrated-From: http://dunkel.pmel.noaa.gov/trac/ferret/ticket/1481

**Comment by karlmsmith** [comment]
**Modified by ansley.b.manke on 5 Jan 2011 19:53 UTC**

**Comment by karlmsmith** [comment]
**Comment by andrew.wittenberg on 2 May 2011 21:07 UTC**
Formatting was lost in the example, here it is:

```
        NOAA/PMEL TMAP
        FERRET v6.7 (nc413snapshot)
        Linux rh5 (gfortran) 2.6.18-238.1.1.el5P - 04/28/11
         2-May-11 17:01     

yes? can mode verify
yes? rep/j=1:3 (def sym a `j`; show sym a; say ($a))
A = "1"
1
A = "2"
2
A = "3"
3
yes? def sym a old
yes? def sym loop rep/j=1:3 (def sym a \`j\`; show sym a; say (\$a))
yes? sho sym loop
LOOP = "rep/j=1:3 (def sym a `j`; show sym a; say ($a))"
yes? ($loop)
A = "1"
old
A = "2"
old
A = "3"
old
```

**Comment by karlmsmith** [comment]
**Comment by ansley.b.manke on 2 May 2011 23:38 UTC**
If we turn on mode verify, we can see a bit more. When we execute the loop by saying

   yes? ($loop)

Ferret gets the value of the symbol ($loop) and at that point the ($a) that's inside it is also evaluated and becomes the value of symbol a at that moment which is "old". 

```
...
yes? def sym a old
yes? define sym loop rep/j=1:3 (def sym a \`j\`; show sym a; say (\$a))

yes? sh sym loop
LOOP = "rep/j=1:3 (def sym a `j`; show sym a; say ($a))"

yes? ($loop)
 !-> rep/j=1:3 (def sym a `j`; show sym a; say old)     <<<< Right here 
!-> REPEAT: J=1
 !-> def sym a 1
A = "1"
old
!-> REPEAT: J=2
...
```

Looking into the code, at the parsing step where ($loop) is evaluated, the `j` is skipped. At this point Ferret does not pay attention to the fact that this is going to be a repeat loop, it's just opening up a symbol which happens to have another symbol in it; something that in general we do want to evaluate.

**Comment by AndrewWittenberg** [comment]
Just ran into this again in our work -- raising the priority.

**Comment by AnsleyManke** [comment]
It seems that the parsing step needs to just keep the contents of the loop intact, not parsing what's inside the parentheses.

**Comment by AnsleyManke** [comment]
This turns out to be fairly simple to fix.  If the whole command being parsed is a symbol,

`yes? ($loop)`

then substitute the contents of that symbol and start all over to parse that.  Previously the parsing just continued, which meant that the ($a) inside the loop was substituted with its value before taking into account that this will be a repeat loop.

```
yes? def sym a old
yes? define sym loop rep/j=1:3 (def sym a \`j\`; show sym a; say (\$a))
yes? ($loop)
 !-> rep/j=1:3 (def sym a `j`; show sym a; say ($a))
!-> REPEAT: J=1
 !-> def sym a 1
A = "1"
 !-> MESSAGE/CONTINUE 1
1
!-> REPEAT: J=2
 !-> def sym a 2
A = "2"
 !-> MESSAGE/CONTINUE 2
2
!-> REPEAT: J=3
 !-> def sym a 3
A = "3"
 !-> MESSAGE/CONTINUE 3
3
```

It's ok as well if the command to substitute and execute ($loop) is on a compound command line,

`yes? def sym a old_a; ($loop)`
