### ISSUE TITLE
scat2gridgauss functions algorithm doesn't match documentation.

### ISSUE THREAD

**Issue by karlmsmith** [NOAA-PMEL/Ferret#903]
**Reported by @AnsleyManke on 5 Feb 2009 22:41 UTC**
The documentation indicates the use of the cutoff parameter to cut down on computation uses computation of distance based up (dx**2 + dy**2). Instead simply looks at MAX(dx, dy). 

Here's the piece from the docs:

```
Wn(xn,yn) = exp{-[(xn-x0)2/(X)2 + (yn-y0)2/(Y)2]}

X and Y in the denominators on the right hand side are the 
mapping scales, arguments XSCALE and YSCALE.
The weight function has a nonzero value everywhere, so all of 
the scattered points in theory could be part of the sum for 
each grid point. To cut computation, the parameter CUTOFF is 
employed. If a cutoff of 2 is used (e.g. CUTOFF* XSCALE=2), 
then the weight function is set to zerowhen Wn< e-4. This occurs 
where distances from the grid point are less than 2 times the 
mapping scales X or Y.
```

But in fact the code just skips a point if dx > cutoff or dy > cutoff.  

Talking with Billy who wrote the gausswt2 code, this is in fact the case - the code does the simpler cutoff. The size of the weights below which the calculation is cut off is of the right magnitude, but the points included in the calculations lie in a box rather than a circular or elliptical shape indicated in the documentation.

We will fix this family of functions, document the change, and make the earlier functions available in case folks don't want the behavior of the function to change.

Migrated-From: http://dunkel.pmel.noaa.gov/trac/ferret/ticket/1631

**Comment by AnsleyManke** [comment]
This was done, 
```
c V62 *ACM* 2/2009 Change the use of cutoff to exclude points from
c            calculation based on weights so that the exclusing 
c            is an ellipse not a box.
```
