### ISSUE TITLE
transformations fail (intermittently) on functions of a variable with a strided axis

### ISSUE THREAD

**Issue by karlmsmith** [NOAA-PMEL/Ferret#965]
**Reported by @AndrewWittenberg on 21 Sep 2009 23:20 UTC**
In trying to work around bug #1691, I ran into this.  Does this give any insight into bug #1691?

Strangely, I only get the error on the first try -- when I repeat the same command, I seem get the plot just fine.  Perhaps something isn't being initialized properly?

(My actual application is slightly more complex -- I'm computing a correlation from 2 time-strided variables that share a time axis.  The definitions and time-striding of the variables can change, and I'd like to then be able to plot the correlation map.  But Ferret is somehow choking on the temporary axes created with the likes of l=1:132:12.)

```
        NOAA/PMEL TMAP
        FERRET v6.203  
        Linux(g77) 2.4.21-32 - 06/26/09
        21-Sep-09 19:09     

yes? use monthly_navy_winds
yes? let a = uwnd[l=1:132:12]
yes? let adev = a-a[l=@ave]
yes? shade adev[l=@max]
 **ERROR: inconsistent sizes of data regions: can't label T axis of A[L=@AVE]
yes? shade adev[l=@max]
```

Migrated-From: http://dunkel.pmel.noaa.gov/trac/ferret/ticket/1693

**Comment by karlmsmith** [comment]
**Comment by ansley.b.manke on 22 Sep 2009 20:21 UTC**
Some comments -

This is not related to bug #1691. 

Also, it goes back to (at least) v5.81, so it is not something we introduced with the native strides syntax. The message happens in  "merge_context". Comparing with how the code works when striding hasn't been used should turn up something.

**Comment by karlmsmith** [comment]
**Comment by andrew.wittenberg on 23 Sep 2009 23:24 UTC**
Not sure if this helps, but here's an example with striding applied *after* the transformation.  The first attempt to plot B fails, while the second one works.  However, B works on the first try if I define A with l=1:132@shf:12 rather than l=@shf:12.

```
        NOAA/PMEL TMAP
        FERRET v6.203
        Linux(g77) 2.4.21-32 - 06/26/09
        23-Sep-09 19:08     

yes? use monthly_navy_winds
yes? let a = uwnd[let b = samplel(a,t[l=1:132:12](x=140w,y=0,l=@shf:12]
yes?))
yes? plot b
 **ERROR: illegal limits: UWND does not exist at L=133
          Axis extremes are L=1:132
yes? plot a
yes? plot b
```

**Comment by karlmsmith** [comment]
**Modified by ansley.b.manke on 5 Jan 2011 19:33 UTC**

**Comment by karlmsmith** [comment]
**Modified by ansley.b.manke on 5 Jan 2011 19:35 UTC**

**Comment by karlmsmith** [comment]
**Modified by ansley.b.manke on 22 Aug 2014 22:15 UTC**

**Comment by AnsleyManke** [comment]
This is fixed in flesh_out_axis.F 

When variables consist of several expressions, there's a "merge-context" process.  For regions defined with strides (dynamic grids in the Ferret terminology), part of this logic was skipped over, so the context was not seen as defined.
