### ISSUE TITLE
LIKE qualifier to copy all attributes from a template with LET and DEFINE AXIS

### ISSUE THREAD

**Issue by karlmsmith** [NOAA-PMEL/Ferret#966]
**Reported by @AndrewWittenberg on 22 Sep 2009 18:28 UTC**
It would be great to have qualifers to copy all variable attributes (title, units) or axis attributes (units, depth_axis, modulo, t0, calendar), unless specifically overriden by other qualifiers.  We could call this qualifier, say, "LIKE" or "TEMPLATE."  I.e. something like this:

LET/LIKE=sst my_sst = sst[x=140w,y=0]
DEFINE AXIS/LIKE=`sst,r=xaxis`/unit="m" x_coarse = x[gx=sst]
DEFINE AXIS/LIKE=`sst,r=taxis`/cal="julian" t_jul = t[gt=sst]

This would greatly simplify generalized scripts that do operations on variables & axes (like spline interpolation, grid decimation, etc.), where the (x,y,z,t) shape of the input may not be known.  The LIKE qualifier would allow us to preserve attributes without explicitly checking for the presence of MODULO, DEPTH, T0 -- currently it takes an awful lot of IF statements to check the various cases, to prevent syntax errors if these attributes are not present. 

Migrated-From: http://dunkel.pmel.noaa.gov/trac/ferret/ticket/1694

**Comment by karlmsmith** [comment]
**Comment by andrew.wittenberg on 22 Sep 2009 18:54 UTC**
Oops, forgot to wrap the examples in a code block.

```
LET/LIKE=sst my_sst = sst[AXIS/LIKE=sst,r=xaxis/unit="m" x_coarse = x[gx=sst](x=140w,y=0]
DEFINE)
DEFINE AXIS/LIKE=sst,r=taxis/cal="julian" t_jul = t[gt=sst]
```

**Comment by karlmsmith** [comment]
**Comment by ansley.b.manke on 30 Sep 2009 21:33 UTC**
There is already one means of doing this for variables. We have this syntax:

SET ATTRIBUTE/LIKE=var1 var2

(which was not documented until the V6.3 version of Ferret)

e.g.

```
yes? USE levitus_climatology
yes? SET ATT/LIKE=salt temp
yes? SHOW ATT/ALL temp
     attributes for dataset: /home/porter/tmap/ferret/linux/fer_dsets/data/levitus_climatology.cdf
 TEMP.missing_value = -1.E+10
 TEMP._FillValue = -1.E+10
 TEMP.long_name = SALINITY 
 TEMP.history = From levitus_climatology 
 TEMP.units = PPT 
```


Which we should also be able to apply to coordinate axes, but which does not yet do that. OR it might be better to do this in terms of DEFINE commands as Andrew suggests.

**Comment by karlmsmith** [comment]
**Modified by ansley.b.manke on 5 Jan 2011 19:49 UTC**

**Comment by karlmsmith** [comment]
**Modified by ansley.b.manke on 5 Jan 2011 22:11 UTC**

**Comment by karlmsmith** [comment]
**Comment by steven.c.hankin on 21 Jan 2013 17:52 UTC**
just a quick comment that I have on a number of occasions wished for DEFINE AXIS/LIKE myself.  The syntax feels very natural.  Probably has to come with the restriction that the new axis and the template axis have the same geo-spatial orientation.

**Comment by karlmsmith** [comment]
**Comment by ansley.b.manke on 23 Jan 2013 23:30 UTC**
See ticket #303

**Comment by AnsleyManke** [comment]
This is done!  e.g.

1) On defining an axis, inherit all attributes from an existing axis. The direction and coordinates must still be specified.  The directions must match. It might seem redundant to require the direction, but this was simpler to implement and removes possible ambiguities.  We are ONLY inheriting attributes not the direction and coordinates.  If attributes are given with qualifiers such as /UNITS those settings take precedence over the inherited ones. 

```
DEFINE AXIS/X/LIKE=existing_axis new_axis = values

DEFINE AXIS/X/LIKE=`sst,r=xaxis`/unit="m" x_coarse = x[gx=sst]
DEFINE AXIS/T/LIKE=`sst,r=taxis`/cal="julian" t_jul = t[gt=sst]
DEFINE AXIS/Z/LIKE=`temp,return=zaxis`/units=meters  zax = {0,5,25,50}
```

2) On defining a variable, inherit the attributes from an existing one.   If attributes are given with qualifiers such as /UNITS those settings take precedence over the inherited ones. Other than the following all the attributes from definitions or a netCDF file are inherited.

* The missing-value and/or _FillValue attributes are NOT inherited, as Ferret processes those on input, keeping only one flag.  Ferret expression syntax fills in with the default Ferret missing-flag, so a missing value must be handled explicitly if it is to be different from the default.

* Likewise scale_factor and add_offset attributes are handled on reading data from netCDF files and are not inherited.

```
LET/LIKE=sst my_sst = sst[x=140w,y=0]
LET/LIKE=sst/TITLE="Water Temperature"  temp = expression
```

(This is a duplicate of #138 )

**Comment by AndrewWittenberg** [comment]
The T0 and TMOD attributes have been overlooked:

```
 	NOAA/PMEL TMAP
 	FERRET v7.32 (optimized)
 	Linux 2.6.32-696.20.1.el6.x86_64 64-bit - 03/19/18
 	24-Mar-18 14:05     

yes? use coads_climatology
yes? def ax/t/like=`sst,r=taxis` tax = t[gt=sst]
yes? say `sst,r=t0`, `sst,r=tmod`
01-JAN-0000 00:00:00, 8765.82
yes? say `t[gt=tax],r=t0`, `t[gt=tax],r=tmod` 
15-JAN-1901,
```

Are there other attributes that aren't yet being inherited, like XMOD?  (It does looks like the "depth" attribute is being inherited.)

**Comment by AndrewWittenberg** [comment]
More issues... First try to copy an axis, e.g.:

```
 	NOAA/PMEL TMAP
 	FERRET v7.32 (optimized)
 	Linux 2.6.32-696.20.1.el6.x86_64 64-bit - 03/19/18
 	24-Mar-18 15:41     

yes? def ax/edge/t=1-jan-0001:1-jan-0004:1/unit=year/cal=noleap tax
yes? def ax/t/like=tax tax2 = t[gt=tax]
yes? sho ax tax
 name       axis              # pts   start                end
 TAX       TIME                 3 r   02-JUL-0001 12:00    02-JUL-0003 12:00
T0 = 01-JAN-0000
CALENDAR = NOLEAP
   Axis span (to cell edges) = 3
yes? sho ax tax2
 name       axis              # pts   start                end
 TAX2      TIME                 3 r   16-JUL-1902 12:00    16-JUL-1904 12:00
T0 = 15-JAN-1901
CALENDAR = NOLEAP
   Axis span (to cell edges) = 3
```

Here the coordinates get messed up due to T0 not getting copied across, as described in my previous comment.  But if we then try to fix this by overriding T0, we get a different problem:

```
yes? def ax/t/like=tax/t0=`t[gt=tax],r=t0` tax2 = t[gt=tax]
Replacing definition of axis TAX2
yes? sho ax tax2
 name       axis              # pts   start                end
 TAX2      TIME                 3 r   01-JUL-0001 20:43    02-JUL-0003 08:22
T0 = 01-JAN-0000
   Axis span (to cell edges) = 3
yes? say `t[gt=tax2],r=cal`
 !-> MESSAGE/CONTINUE GREGORIAN
GREGORIAN
```

Now the calendar attribute has spuriously switched from NOLEAP to GREGORIAN!

**Comment by AndrewWittenberg** [comment]
More fun -- we can actually crash Ferret, if we make a mistake in a seemingly independent command:

```
 	NOAA/PMEL TMAP
 	FERRET v7.32 (optimized)
 	Linux 2.6.32-696.20.1.el6.x86_64 64-bit - 03/19/18
 	24-Mar-18 15:50     

yes? def ax/edge/t=1-jan-0001:1-jan-0004:1/unit=year/cal=noleap tax
yes? def ax/t/like=tax tax2 = tax
 **ERROR: variable unknown or not in data set: TAX
yes? sho ax tax
 name       axis              # pts   start                end
 TAX       TIME                 3 r   02-JUL-0001 12:00    02-JUL-0003 12:00
T0 = 01-JAN-0000
CALENDAR = NOLEAP
   Axis span (to cell edges) = 3
**ERROR Ferret crash; signal = 11
```

**Comment by AnsleyManke** [comment]
This is all corrected.   A DEFINE AXIS/LIKE= command inherits everything from the parent axis, and then uses the qualifiers and coordinate data to customize things.  The Time origin and modulo characteristics weren't handled right.  And, as to the last comment above, the axis needs to not be "finished" correctly before it's name is stored, which is the final step in defining an axis.  Encountering an error should return us to the previous state.  that's now fixed too.

**Comment by AnsleyManke** [comment]
An additional comment -- for documentation.  The modulo-axis length is not inherited from the child axis, but is computed from the coordinates and the the coordinate units, plus the calendar type if it's a time axis.  

Especially if the coordinate data is irregular, then the definition needs to be done with care, with DEFINE AXIS/LIKE or with any other DEFINE AXIS command.

Look at the modulo-axis length in this example using the coordinates from the pre-defined axis MONTH_JULIAN time axis. 

```
yes? show axis month_julian
 name       axis              # pts   start                end
 MONTH_JULIAN TIME             12mi   16-JAN 12:00         15-DEC 18:00
T0 = 01-JAN-0000 00:00:00
CALENDAR = JULIAN
   Axis span (to cell edges) = 365.25 (modulo length = axis span)

yes? ! Note how the modulo length of the new axis is shorter than month_julian's.
yes? define axis/t/like=month_julian tax = t[gt=month_julian]
yes? sh axis tax
 name       axis              # pts   start                end
 TAX       TIME                12mi   16-JAN 12:00         15-DEC 18:00
T0 = 01-JAN-0000 00:00:00
CALENDAR = JULIAN
   Axis span (to cell edges) = 364.375 (modulo length = axis span)
 
yes? ! But it's correct if we define the axis from the edges.

yes? define axis/t/like=month_julian/edges tax = box_edges(t[gt=month_julian])
Replacing definition of axis TAX
yes? sh axis tax
 name       axis              # pts   start                end
 TAX       TIME                12mi   16-JAN 12:00         15-DEC 18:00
T0 = 01-JAN-0000 00:00:00
CALENDAR = JULIAN
   Axis span (to cell edges) = 365.25 (modulo length = axis span)

```

Or the modulo length can be explicitly set with the DEFINE AXIS/MODULO qualifier, on either an initial DEFINE AXIS or on a DEFINE AXIS/LIKE= command.  But here that wouldn't get us the same axis definition.

**Comment by AnsleyManke** [comment]
Closing this - new tests are added.
